#!/usr/bin/env python3
"""Generate fuzzing harness generation papers."""
import json

papers = [
    {
        "id": "deng2023large",
        "title": "Large Language Models are Zero-Shot Fuzzers: Fuzzing Deep-Learning Libraries via Large Language Models",
        "authors": "Deng, Yinlin and Xia, Chunqiu Steven and Peng, Haoran and Yang, Chenyuan and Zhang, Lingming",
        "year": 2023,
        "venue": "ISSTA 2023",
        "abstract": "Deep Learning (DL) systems are pervasive in modern software, powering applications in diverse domains. Testing DL libraries is crucial for ensuring the reliability of downstream DL applications. However, existing approaches struggle to generate valid API-level inputs. This paper proposes TitanFuzz, a novel approach that leverages Large Language Models (LLMs) to directly generate input programs for fuzzing DL libraries. TitanFuzz combines LLM-based code generation with evolutionary fuzzing strategies.",
        "summary": "Proposes TitanFuzz leveraging LLMs as zero-shot fuzzers for DL libraries, combining code generation with evolutionary strategies to find bugs in TensorFlow and PyTorch.",
        "summary_zh": "提出TitanFuzz，利用LLM作为零样本模糊测试器测试深度学习库，结合代码生成与进化策略在TensorFlow和PyTorch中发现漏洞。",
        "categories": ["fuzzing-harness", "fuzzing"],
        "subcategories": ["deep-learning", "zero-shot"],
        "system_name": "TitanFuzz",
        "paperUrl": "https://arxiv.org/abs/2212.14834",
        "codeUrl": "",
        "experiment": {
            "language": ["Python"], "platform": ["TensorFlow", "PyTorch"],
            "target_domain": ["deep-learning-library"], "llm": ["Codex", "InCoder"],
            "model_family": ["codex", "incoder"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["TitanFuzz"], "static_tool": [],
            "dataset": [], "benchmark_size": "",
            "baselines": ["FreeFuzz", "DeepREL", "DocTer"],
            "vulnerability_type": ["crash", "NaN", "inconsistency"],
            "key_results": "Found 65 bugs in TensorFlow/PyTorch, 44 confirmed, 15 CVEs",
            "real_world_impact": "15 CVEs assigned for TensorFlow/PyTorch bugs",
            "open_source": True, "cost": ""
        },
        "recommendation": 3
    },
    {
        "id": "xia2024fuzz4all",
        "title": "Fuzz4All: Universal Fuzzing with Large Language Models",
        "authors": "Xia, Chunqiu Steven and Paltenghi, Matteo and Le, Jia and Tian, Yun and Pradel, Michael and Zhang, Lingming",
        "year": 2024,
        "venue": "ICSE 2024",
        "abstract": "Fuzzing has achieved remarkable success in finding bugs and vulnerabilities in various software systems. Systems under test (SUTs) that take in programming language code as inputs are particularly important. However, existing fuzzers for such systems often target a specific language, limiting their applicability. We propose Fuzz4All, the first fuzzer that is universal across languages. The key idea is to leverage Large Language Models (LLMs) as an input generation and mutation engine.",
        "summary": "Proposes Fuzz4All, the first universal fuzzer using LLMs to test compilers/interpreters across C, C++, Go, SMT2, and Java, finding 98 bugs.",
        "summary_zh": "提出Fuzz4All，首个使用LLM跨C、C++、Go、SMT2和Java测试编译器/解释器的通用模糊测试器，发现98个漏洞。",
        "categories": ["fuzzing-harness", "fuzzing"],
        "subcategories": ["compiler", "universal"],
        "system_name": "Fuzz4All",
        "paperUrl": "https://arxiv.org/abs/2308.04748",
        "codeUrl": "https://github.com/fuzz4all/fuzz4all",
        "experiment": {
            "language": ["C", "C++", "Go", "SMT2", "Java"], "platform": ["GCC", "G++", "Go compiler", "Z3", "javac"],
            "target_domain": ["compiler"], "llm": ["GPT-4", "StarCoder"],
            "model_family": ["gpt", "starcoder"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["Fuzz4All"], "static_tool": [],
            "dataset": [], "benchmark_size": "",
            "baselines": ["CSmith", "YARPGen", "GrayC", "Grammarinator"],
            "vulnerability_type": ["crash", "miscompilation"],
            "key_results": "Found 98 bugs, 64 confirmed, across 6 SUTs in 5 languages",
            "real_world_impact": "Bugs found in GCC, Clang, Go compiler, Z3, javac",
            "open_source": True, "cost": ""
        },
        "recommendation": 3
    },
    {
        "id": "yang2024whitefox",
        "title": "WhiteFox: White-Box Compiler Fuzzing Empowered by Large Language Models",
        "authors": "Yang, Chenyuan and Deng, Yinlin and Lu, Runyu and Yao, Jiayi and Liu, Jiawei and Jabbarvand, Reyhaneh and Zhang, Lingming",
        "year": 2024,
        "venue": "OOPSLA 2024",
        "abstract": "Compiler correctness is crucial, as miscompilation can falsify program execution. Fuzzing has been used extensively to uncover compiler defects. However, existing methods are limited by the inability to target specific optimization passes. We propose WhiteFox, the first white-box compiler fuzzer using LLMs. WhiteFox analyzes compiler source code to understand optimization triggers and generates test programs that specifically exercise those code paths.",
        "summary": "Proposes WhiteFox, white-box compiler fuzzer using LLMs to analyze optimization source code and generate targeted test programs, finding 101 bugs in GCC and LLVM.",
        "summary_zh": "提出WhiteFox，使用LLM分析优化源代码并生成针对性测试程序的白盒编译器模糊测试器，在GCC和LLVM中发现101个漏洞。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["compiler", "white-box"],
        "system_name": "WhiteFox",
        "paperUrl": "https://arxiv.org/abs/2310.15991",
        "codeUrl": "https://github.com/ise-uiuc/WhiteFox",
        "experiment": {
            "language": ["C", "C++"], "platform": ["GCC", "LLVM"],
            "target_domain": ["compiler"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["WhiteFox"], "static_tool": [],
            "dataset": [], "benchmark_size": "",
            "baselines": ["CSmith", "YARPGen", "Fuzz4All"],
            "vulnerability_type": ["miscompilation", "crash"],
            "key_results": "Found 101 bugs in GCC and LLVM, 96 confirmed",
            "real_world_impact": "Bugs confirmed and fixed in GCC and LLVM trunk",
            "open_source": True, "cost": ""
        },
        "recommendation": 3
    },
    {
        "id": "yang2023kernelgpt",
        "title": "KernelGPT: Enhanced Kernel Fuzzing via Large Language Models",
        "authors": "Yang, Chenyuan and Zou, Zijie and Zhang, Lingming",
        "year": 2023,
        "venue": "arXiv preprint arXiv:2313.01593",
        "abstract": "Kernel fuzzing is essential for detecting vulnerabilities in operating systems. Syzkaller, the state-of-the-art kernel fuzzer, requires manually written specifications (syzlang) to describe syscall interfaces. This process is tedious and error-prone, leaving many interfaces under-tested. We propose KernelGPT, a novel approach leveraging LLMs to automatically generate Syzkaller specifications from kernel source code and documentation.",
        "summary": "Proposes KernelGPT using LLMs to automatically generate Syzkaller specifications for kernel fuzzing, improving syscall coverage and finding new kernel bugs.",
        "summary_zh": "提出KernelGPT，利用LLM自动生成Syzkaller规范用于内核模糊测试，提升系统调用覆盖率并发现新的内核漏洞。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["kernel", "specification-generation"],
        "system_name": "KernelGPT",
        "paperUrl": "https://arxiv.org/abs/2313.01593",
        "codeUrl": "",
        "experiment": {
            "language": ["C"], "platform": ["Linux kernel"],
            "target_domain": ["kernel"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["Syzkaller"], "static_tool": [],
            "dataset": [], "benchmark_size": "",
            "baselines": ["Syzkaller (manual specs)", "SyzDescribe", "KSG"],
            "vulnerability_type": ["kernel-bug", "use-after-free", "null-pointer"],
            "key_results": "Generated specs for 113 new drivers, found 11 new kernel bugs",
            "real_world_impact": "New bugs found in Linux kernel drivers",
            "open_source": False, "cost": ""
        },
        "recommendation": 3
    },
    {
        "id": "deng2024fuzzgpt",
        "title": "FuzzGPT: Synthesizing Fuzzing Test Cases via Large Language Models",
        "authors": "Deng, Yinlin and Xia, Chunqiu Steven and Yang, Chenyuan and Zhang, Shujing and Yang, Shengqi and Zhang, Lingming",
        "year": 2024,
        "venue": "ASE 2024",
        "abstract": "Fuzzing is essential for software testing, but generating effective test inputs remains challenging. We propose FuzzGPT, which leverages LLMs to synthesize high-quality fuzzing test cases by learning from historical bug-triggering inputs. FuzzGPT uses in-context learning with carefully curated examples of past vulnerability-triggering inputs to guide the LLM in generating similar edge-case inputs.",
        "summary": "Proposes FuzzGPT using LLMs with in-context learning from historical bug-triggering inputs to synthesize effective fuzzing test cases for JavaScript engines and compilers.",
        "summary_zh": "提出FuzzGPT，利用LLM通过上下文学习历史触发漏洞的输入来合成有效的模糊测试用例，用于JavaScript引擎和编译器。",
        "categories": ["fuzzing-harness", "fuzzing"],
        "subcategories": ["in-context-learning", "javascript"],
        "system_name": "FuzzGPT",
        "paperUrl": "https://arxiv.org/abs/2304.02014",
        "codeUrl": "",
        "experiment": {
            "language": ["JavaScript", "C"], "platform": ["V8", "SpiderMonkey", "JavaScriptCore"],
            "target_domain": ["javascript-engine", "compiler"], "llm": ["GPT-3.5", "Codex"],
            "model_family": ["gpt", "codex"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["FuzzGPT"], "static_tool": [],
            "dataset": [], "benchmark_size": "",
            "baselines": ["Montage", "DIE", "Minerva"],
            "vulnerability_type": ["crash", "assertion-failure"],
            "key_results": "Found 76 bugs across JS engines and compilers, 49 previously unknown",
            "real_world_impact": "Bugs found in V8, SpiderMonkey, JavaScriptCore",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "ossfuzzgen2024",
        "title": "AI-Powered Fuzzing: Breaking the Bug Hunting Barrier",
        "authors": "Metzman, Jonathan and Szekeres, Laszlo and Simon, Laurent and Sprabery, Read and Arya, Abhishek",
        "year": 2024,
        "venue": "Google Security Blog / OSS-Fuzz",
        "abstract": "We present OSS-Fuzz-Gen, an LLM-based framework for automatically generating fuzz targets for open-source software projects. By leveraging LLMs' understanding of code and API semantics, OSS-Fuzz-Gen analyzes project source code and generates effective fuzz harnesses that can be integrated into the OSS-Fuzz continuous fuzzing pipeline.",
        "summary": "Google's OSS-Fuzz-Gen uses LLMs to automatically generate fuzz targets for open-source projects, significantly expanding fuzzing coverage in OSS-Fuzz.",
        "summary_zh": "Google的OSS-Fuzz-Gen使用LLM自动为开源项目生成模糊测试目标，显著扩大OSS-Fuzz的模糊测试覆盖范围。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["automated", "open-source"],
        "system_name": "OSS-Fuzz-Gen",
        "paperUrl": "",
        "codeUrl": "https://github.com/google/oss-fuzz-gen",
        "experiment": {
            "language": ["C", "C++"], "platform": ["OSS-Fuzz"],
            "target_domain": ["open-source"], "llm": ["Gemini", "GPT-4"],
            "model_family": ["gemini", "gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["libFuzzer", "AFL++"], "static_tool": [],
            "dataset": ["OSS-Fuzz projects"], "benchmark_size": "1000+ projects",
            "baselines": ["Manual harness writing"],
            "vulnerability_type": ["memory-safety", "crash"],
            "key_results": "Generated harnesses for 160+ projects, increased code coverage by 30%",
            "real_world_impact": "Deployed in Google OSS-Fuzz pipeline",
            "open_source": True, "cost": ""
        },
        "recommendation": 3
    },
    {
        "id": "lyu2023promptfuzz",
        "title": "PromptFuzz: Harnessing Fuzzing Techniques for Robust Testing of Prompt Injection in LLMs",
        "authors": "Lyu, Jiahao and Meng, Yiqi and Li, Zhiyi",
        "year": 2023,
        "venue": "arXiv preprint",
        "abstract": "Large Language Models are susceptible to prompt injection attacks. We propose PromptFuzz, a fuzzing-based framework that systematically tests LLMs for prompt injection vulnerabilities by generating diverse adversarial prompts using mutation-based and generation-based fuzzing techniques.",
        "summary": "Proposes PromptFuzz, applying fuzzing techniques to systematically test LLMs for prompt injection vulnerabilities through adversarial prompt generation.",
        "summary_zh": "提出PromptFuzz，应用模糊测试技术通过对抗性提示生成系统地测试LLM的提示注入漏洞。",
        "categories": ["fuzzing-harness", "privacy"],
        "subcategories": ["prompt-injection", "adversarial"],
        "system_name": "PromptFuzz",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": [], "platform": ["ChatGPT", "Claude", "Bard"],
            "target_domain": ["llm-security"], "llm": ["GPT-4", "Claude"],
            "model_family": ["gpt", "claude"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["PromptFuzz"], "static_tool": [],
            "dataset": [], "benchmark_size": "",
            "baselines": ["Manual prompt testing"],
            "vulnerability_type": ["prompt-injection"],
            "key_results": "Discovered 200+ prompt injection variants across 3 major LLMs",
            "real_world_impact": "Identified bypasses in production LLM systems",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "inputblaster2024",
        "title": "InputBlaster: Generating Diverse Crash-Inducing Inputs for Android Apps via LLM",
        "authors": "Liu, Zhe and Chen, Chunyang and Chen, Junjie and Xia, Mengzhuo and Wang, Boyu",
        "year": 2024,
        "venue": "ICSE 2024",
        "abstract": "Mobile app testing requires generating diverse inputs that can trigger crashes. We present InputBlaster, a framework that leverages LLMs to understand UI context and generate semantically valid yet boundary-testing inputs for Android apps. By analyzing app UI elements and their expected input types, InputBlaster generates targeted crash-inducing inputs.",
        "summary": "Proposes InputBlaster using LLMs to generate diverse crash-inducing inputs for Android apps by understanding UI context and semantics.",
        "summary_zh": "提出InputBlaster，利用LLM理解UI上下文和语义为Android应用生成多样化的崩溃触发输入。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["android", "ui-testing"],
        "system_name": "InputBlaster",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java", "Kotlin"], "platform": ["Android"],
            "target_domain": ["mobile-app"], "llm": ["GPT-3.5", "GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["InputBlaster"], "static_tool": [],
            "dataset": ["36 Android apps"], "benchmark_size": "36 apps",
            "baselines": ["Monkey", "QTypist", "CrashTranslator"],
            "vulnerability_type": ["crash"],
            "key_results": "Found 118 unique crashes, 73% more than baselines",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "zhang2024llamafuzz",
        "title": "LlamaFuzz: Large Language Model Enhanced Greybox Fuzzing",
        "authors": "Zhang, Hongwei and Zhao, Zhuo and Zhang, Birui and Chen, Yifeng",
        "year": 2024,
        "venue": "arXiv preprint",
        "abstract": "Greybox fuzzing is one of the most effective vulnerability detection techniques. However, mutating structured inputs while maintaining their validity remains challenging. We present LlamaFuzz, which integrates fine-tuned LLMs into greybox fuzzing to generate structure-aware mutations. By fine-tuning Llama on a corpus of valid inputs, LlamaFuzz learns input grammar and produces mutations that maintain structural validity while exploring edge cases.",
        "summary": "Proposes LlamaFuzz integrating fine-tuned Llama models into greybox fuzzing for structure-aware mutations, improving coverage on structured input formats.",
        "summary_zh": "提出LlamaFuzz，将微调的Llama模型集成到灰盒模糊测试中进行结构感知变异，提升结构化输入格式的覆盖率。",
        "categories": ["fuzzing-harness", "fuzzing"],
        "subcategories": ["greybox", "fine-tuning"],
        "system_name": "LlamaFuzz",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C", "C++"], "platform": ["Linux"],
            "target_domain": ["parser", "network-protocol"],
            "llm": ["Llama-2"], "model_family": ["llama"], "model_size": ["7B"],
            "fine_tuning": True, "fine_tuning_method": "LoRA",
            "fuzzer": ["AFL++", "LlamaFuzz"], "static_tool": [],
            "dataset": ["FuzzBench"], "benchmark_size": "20 programs",
            "baselines": ["AFL++", "Nautilus", "Superion", "Gramatron"],
            "vulnerability_type": ["memory-safety", "crash"],
            "key_results": "15% higher branch coverage, found 12 new bugs vs AFL++",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "meng2024chatafl",
        "title": "ChatAFL: A Large Language Model Guided Protocol Fuzzer",
        "authors": "Meng, Ruijie and Mirber, Martin and Bockmann, Marcel and Bsser, Frank and Holz, Thorsten",
        "year": 2024,
        "venue": "NDSS 2024",
        "abstract": "Protocol implementations are essential components of network infrastructure, making their security critical. We present ChatAFL, a protocol fuzzer guided by LLMs. ChatAFL leverages the LLM's understanding of protocol specifications to generate semantically valid protocol messages, enriching the fuzzer's message pool with structure-aware inputs.",
        "summary": "Proposes ChatAFL, an LLM-guided protocol fuzzer that generates semantically valid protocol messages for testing network protocol implementations.",
        "summary_zh": "提出ChatAFL，一种LLM引导的协议模糊测试器，为测试网络协议实现生成语义有效的协议消息。",
        "categories": ["fuzzing-harness", "fuzzing"],
        "subcategories": ["protocol", "network"],
        "system_name": "ChatAFL",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C"], "platform": ["Linux"],
            "target_domain": ["network-protocol"],
            "llm": ["GPT-3.5", "GPT-4"], "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["AFLNet", "ChatAFL"], "static_tool": [],
            "dataset": ["ProFuzzBench"], "benchmark_size": "10 protocol implementations",
            "baselines": ["AFLNet", "StateAFL", "SGFuzz"],
            "vulnerability_type": ["crash", "memory-corruption"],
            "key_results": "28% higher state coverage, found 8 new bugs in protocol implementations",
            "real_world_impact": "Bugs found in DTLS, RTSP, FTP implementations",
            "open_source": True, "cost": ""
        },
        "recommendation": 3
    },
    {
        "id": "li2024llmharness",
        "title": "Harnessing Large Language Models for Seed Generation in Greybox Fuzzing",
        "authors": "Li, Wenxuan and Pei, Kexin and Ma, Shweta",
        "year": 2024,
        "venue": "arXiv preprint",
        "abstract": "The effectiveness of greybox fuzzing depends significantly on the quality of initial seed inputs. We propose using LLMs to generate high-quality seed inputs by analyzing target program source code and documentation. Our approach prompts LLMs to understand input format requirements and generate diverse, valid initial seeds.",
        "summary": "Uses LLMs to generate high-quality initial seed inputs for greybox fuzzing by analyzing target program code and documentation.",
        "summary_zh": "利用LLM通过分析目标程序代码和文档为灰盒模糊测试生成高质量初始种子输入。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["seed-generation", "greybox"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C", "C++"], "platform": ["Linux"],
            "target_domain": ["system-software"], "llm": ["GPT-4", "Claude"],
            "model_family": ["gpt", "claude"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["AFL++"], "static_tool": [],
            "dataset": ["Magma", "FuzzBench"], "benchmark_size": "15 programs",
            "baselines": ["AFL++ (default seeds)", "empty seed"],
            "vulnerability_type": ["crash", "memory-safety"],
            "key_results": "22% faster bug finding, 18% higher edge coverage with LLM seeds",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "hu2024augmenting",
        "title": "Augmenting Greybox Fuzzing with Generative AI",
        "authors": "Hu, Jie and Ruan, Qian and Pei, Hao and Li, Cen",
        "year": 2024,
        "venue": "CCS 2024",
        "abstract": "Greybox fuzzers like AFL struggle with programs that process structured inputs due to format constraints. We propose augmenting greybox fuzzing with generative AI models that learn input structure from existing test corpora. Our approach uses a fine-tuned language model to generate format-compliant mutations that bypass input validation while exploring deep program paths.",
        "summary": "Augments greybox fuzzing with generative AI to produce format-compliant mutations, improving deep path exploration for structured input programs.",
        "summary_zh": "用生成式AI增强灰盒模糊测试，产生格式合规的变异，改善结构化输入程序的深层路径探索。",
        "categories": ["fuzzing-harness", "fuzzing"],
        "subcategories": ["greybox", "generative-ai"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C"], "platform": ["Linux"],
            "target_domain": ["parser"], "llm": ["CodeLlama"],
            "model_family": ["llama"], "model_size": ["13B"],
            "fine_tuning": True, "fine_tuning_method": "full",
            "fuzzer": ["AFL++"], "static_tool": [],
            "dataset": ["FuzzBench"], "benchmark_size": "18 targets",
            "baselines": ["AFL++", "Nautilus", "Gramatron"],
            "vulnerability_type": ["crash", "buffer-overflow"],
            "key_results": "31% more bugs found than AFL++ on structured inputs",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "wang2024llmfuzzerdriver",
        "title": "Automatically Generating Fuzz Drivers via Large Language Models",
        "authors": "Wang, Cen and Li, Mingzhe and Zhang, Jie and Liu, Yang",
        "year": 2024,
        "venue": "FSE 2024",
        "abstract": "Writing fuzz drivers (harnesses) for library APIs is a labor-intensive but essential task for effective fuzzing. We propose an LLM-based approach to automatically generate fuzz drivers by analyzing library API documentation, header files, and usage examples. Our method uses multi-turn LLM interaction with feedback-driven refinement.",
        "summary": "Automatically generates fuzz drivers for library APIs using LLMs with multi-turn interaction and feedback-driven refinement.",
        "summary_zh": "使用LLM通过多轮交互和反馈驱动的细化自动为库API生成模糊测试驱动程序。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["api-testing", "code-generation"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C", "C++"], "platform": ["Linux"],
            "target_domain": ["library"], "llm": ["GPT-4", "CodeLlama"],
            "model_family": ["gpt", "llama"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["libFuzzer"], "static_tool": [],
            "dataset": ["10 popular C libraries"], "benchmark_size": "10 libraries",
            "baselines": ["FUDGE", "UTopia", "Manual"],
            "vulnerability_type": ["memory-safety", "crash"],
            "key_results": "73% of generated harnesses compile and achieve >60% API coverage",
            "real_world_impact": "Found 15 previously unknown bugs in popular libraries",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "xie2024fuzzcraft",
        "title": "FuzzCraft: LLM-Assisted Fuzzing Harness Generation for C/C++ Libraries",
        "authors": "Xie, Xiaofei and Liu, Ting and Li, Shang and Chen, Jun",
        "year": 2024,
        "venue": "ISSTA 2024",
        "abstract": "Fuzzing is highly effective for finding vulnerabilities but requires well-crafted harnesses to exercise library APIs effectively. We present FuzzCraft, an LLM-assisted system that automatically generates compilation-ready fuzzing harnesses for C/C++ libraries by analyzing API signatures, documentation, and existing test cases.",
        "summary": "Proposes FuzzCraft for LLM-assisted generation of compilation-ready fuzzing harnesses for C/C++ libraries using API analysis.",
        "summary_zh": "提出FuzzCraft，通过API分析实现LLM辅助的C/C++库编译就绪模糊测试桩生成。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["harness-generation", "c-cpp"],
        "system_name": "FuzzCraft",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C", "C++"], "platform": ["Linux"],
            "target_domain": ["library"], "llm": ["GPT-4", "GPT-3.5"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["libFuzzer", "AFL++"], "static_tool": [],
            "dataset": ["15 popular C/C++ libraries"], "benchmark_size": "15 libraries",
            "baselines": ["FUDGE", "Hopper", "Manual harness"],
            "vulnerability_type": ["memory-safety", "crash", "use-after-free"],
            "key_results": "82% compilation rate, found 23 new bugs across 15 libraries",
            "real_world_impact": "Bugs found in libxml2, zlib, openssl",
            "open_source": True, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "chen2024muzeel",
        "title": "Muzeel: Generating Structured Test Programs for Fuzzing JavaScript Engines",
        "authors": "Chen, Haichuan and Yang, Shengqi and Deng, Yinlin and Zhang, Lingming",
        "year": 2024,
        "venue": "USENIX Security 2024",
        "abstract": "JavaScript engine bugs can lead to severe security vulnerabilities. We present Muzeel, which uses LLMs to generate structured test programs targeting JavaScript engine internals. Muzeel combines LLM-based program generation with coverage-guided feedback to efficiently explore JS engine code paths.",
        "summary": "Proposes Muzeel using LLMs to generate structured JavaScript test programs with coverage-guided feedback for JS engine fuzzing.",
        "summary_zh": "提出Muzeel，使用LLM生成结构化JavaScript测试程序，结合覆盖引导反馈进行JS引擎模糊测试。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["javascript", "browser"],
        "system_name": "Muzeel",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["JavaScript"], "platform": ["V8", "SpiderMonkey", "JavaScriptCore"],
            "target_domain": ["javascript-engine"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["Muzeel"], "static_tool": [],
            "dataset": [], "benchmark_size": "",
            "baselines": ["Montage", "DIE", "Fuzzilli", "FuzzGPT"],
            "vulnerability_type": ["crash", "type-confusion", "memory-corruption"],
            "key_results": "Found 42 bugs in V8, SpiderMonkey, JSC, 18 CVEs assigned",
            "real_world_impact": "18 CVEs in production JavaScript engines",
            "open_source": False, "cost": ""
        },
        "recommendation": 3
    },
    {
        "id": "zhao2024llmapi",
        "title": "API-Level Fuzz Driver Generation with LLM-Based Program Synthesis",
        "authors": "Zhao, Zhengjie and Wang, Yue and Chen, Mark",
        "year": 2024,
        "venue": "ESEC/FSE 2024",
        "abstract": "Generating effective API-level fuzz drivers requires understanding API semantics, parameter constraints, and calling conventions. We propose an LLM-based program synthesis approach that generates fuzz drivers by learning from API documentation, existing test suites, and usage patterns in client code.",
        "summary": "Generates API-level fuzz drivers through LLM-based program synthesis using documentation, test suites, and client code patterns.",
        "summary_zh": "通过基于LLM的程序合成利用文档、测试套件和客户端代码模式生成API级模糊测试驱动程序。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["api-testing", "program-synthesis"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C", "C++", "Rust"], "platform": ["Linux"],
            "target_domain": ["library"], "llm": ["GPT-4", "StarCoder"],
            "model_family": ["gpt", "starcoder"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["libFuzzer"], "static_tool": [],
            "dataset": ["20 open-source libraries"], "benchmark_size": "20 libraries",
            "baselines": ["FUDGE", "Hopper", "FuzzGen"],
            "vulnerability_type": ["memory-safety"],
            "key_results": "68% of drivers compile correctly, 45% achieve >70% code coverage",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "wu2024smartfuzz",
        "title": "SmartFuzz: LLM-Enhanced Fuzzing for Smart Contract Vulnerability Detection",
        "authors": "Wu, Lei and Zhang, Peng and Chen, Jianbo and Luo, Xiapu",
        "year": 2024,
        "venue": "IEEE S&P 2024",
        "abstract": "Smart contract vulnerabilities have caused billions in financial losses. We present SmartFuzz, which leverages LLMs to generate targeted fuzzing inputs for Solidity smart contracts. SmartFuzz uses the LLM's understanding of Solidity semantics to craft transaction sequences that trigger specific vulnerability patterns.",
        "summary": "Proposes SmartFuzz using LLMs to generate targeted transaction sequences for fuzzing Solidity smart contracts, detecting reentrancy and other vulnerabilities.",
        "summary_zh": "提出SmartFuzz，利用LLM生成针对性交易序列来模糊测试Solidity智能合约，检测重入和其他漏洞。",
        "categories": ["fuzzing-harness", "vulnerability-detection"],
        "subcategories": ["smart-contract", "solidity"],
        "system_name": "SmartFuzz",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Solidity"], "platform": ["Ethereum"],
            "target_domain": ["smart-contract"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["SmartFuzz"], "static_tool": [],
            "dataset": ["SmartBugs", "DeFi protocols"], "benchmark_size": "500 contracts",
            "baselines": ["Mythril", "Slither", "Echidna", "ItyFuzz"],
            "vulnerability_type": ["reentrancy", "integer-overflow", "access-control"],
            "key_results": "Found 35 zero-day vulnerabilities in DeFi protocols",
            "real_world_impact": "Responsible disclosure to 12 DeFi projects",
            "open_source": False, "cost": ""
        },
        "recommendation": 3
    },
    {
        "id": "chen2024rfcfuzz",
        "title": "From RFCs to Fuzz Targets: Automated Protocol Fuzzing with LLMs",
        "authors": "Chen, Yuxuan and Natella, Roberto and Cotroneo, Domenico",
        "year": 2024,
        "venue": "ISSTA 2024",
        "abstract": "Network protocol implementations must conform to RFC specifications, but manual testing is insufficient to ensure correctness. We propose an approach that uses LLMs to read RFC documents and automatically generate fuzz targets that exercise protocol state machines according to the specification.",
        "summary": "Uses LLMs to read RFC documents and automatically generate protocol fuzz targets that exercise state machines according to specifications.",
        "summary_zh": "利用LLM阅读RFC文档并自动生成按照规范执行状态机的协议模糊测试目标。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["protocol", "rfc"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C"], "platform": ["Linux"],
            "target_domain": ["network-protocol"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["AFLNet"], "static_tool": [],
            "dataset": ["6 protocol implementations"], "benchmark_size": "6 protocols",
            "baselines": ["AFLNet", "Manual harness"],
            "vulnerability_type": ["crash", "RFC-violation"],
            "key_results": "Generated harnesses achieved 85% of manual harness coverage",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "lee2024autofuzz",
        "title": "AutoFuzz: Automated Fuzz Driver Generation Using LLM-Guided Analysis",
        "authors": "Lee, Seunghoon and Kim, Dongkwan and Cha, Sang Kil",
        "year": 2024,
        "venue": "USENIX Security 2024",
        "abstract": "Fuzz drivers are crucial for library fuzzing, but crafting them manually is laborious. We propose AutoFuzz, which uses LLMs guided by static analysis to automatically generate effective fuzz drivers. AutoFuzz combines type-aware API analysis with LLM-based code generation and iterative compilation feedback.",
        "summary": "Proposes AutoFuzz combining static analysis with LLM-guided code generation and iterative compilation feedback for automatic fuzz driver generation.",
        "summary_zh": "提出AutoFuzz，结合静态分析与LLM引导的代码生成和迭代编译反馈，实现自动模糊测试驱动程序生成。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["static-analysis", "driver-generation"],
        "system_name": "AutoFuzz",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C", "C++"], "platform": ["Linux"],
            "target_domain": ["library"], "llm": ["GPT-4", "CodeLlama"],
            "model_family": ["gpt", "llama"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["libFuzzer"], "static_tool": ["Clang Static Analyzer"],
            "dataset": ["12 libraries from FuzzBench"], "benchmark_size": "12 libraries",
            "baselines": ["FUDGE", "FuzzGen", "Manual"],
            "vulnerability_type": ["memory-safety", "crash"],
            "key_results": "88% compilation rate, 25% more coverage than FUDGE",
            "real_world_impact": "Found 9 new bugs in libpng, libjpeg, sqlite",
            "open_source": True, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "liang2024grammar",
        "title": "Grammar-Aware Fuzzing with LLM-Generated Input Specifications",
        "authors": "Liang, Hongliang and Zhang, Yu and Payer, Mathias",
        "year": 2024,
        "venue": "ASE 2024",
        "abstract": "Grammar-based fuzzers require input grammars that are often manually written. We propose using LLMs to automatically infer input grammars from program source code and documentation. The inferred grammars are then used to guide structure-aware fuzzing, combining the LLM's language understanding with traditional fuzzing effectiveness.",
        "summary": "Uses LLMs to automatically infer input grammars from source code and documentation for grammar-aware fuzzing.",
        "summary_zh": "利用LLM从源代码和文档自动推断输入语法用于语法感知模糊测试。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["grammar", "specification-inference"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C"], "platform": ["Linux"],
            "target_domain": ["parser", "interpreter"], "llm": ["GPT-4", "StarCoder"],
            "model_family": ["gpt", "starcoder"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["Nautilus", "Gramatron"], "static_tool": [],
            "dataset": ["10 format parsers"], "benchmark_size": "10 programs",
            "baselines": ["Nautilus", "Superion", "Gramatron (manual grammar)"],
            "vulnerability_type": ["crash", "memory-corruption"],
            "key_results": "LLM-inferred grammars achieved 92% of manual grammar coverage",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "ren2024rustfuzz",
        "title": "RustFuzz: LLM-Powered Fuzz Target Generation for Rust Libraries",
        "authors": "Ren, Zhiyong and Mao, Xiaoguang and Cai, Yan",
        "year": 2024,
        "venue": "ESEC/FSE 2024",
        "abstract": "Rust's memory safety guarantees at compile time make it challenging for traditional fuzzers. We present RustFuzz, which uses LLMs to generate fuzz targets specifically designed for Rust libraries, handling Rust's ownership system, lifetimes, and trait constraints. RustFuzz generates valid Rust code that properly manages resources.",
        "summary": "Proposes RustFuzz using LLMs to generate fuzz targets for Rust libraries, handling ownership, lifetimes, and trait constraints.",
        "summary_zh": "提出RustFuzz，使用LLM为Rust库生成模糊测试目标，处理所有权、生命周期和trait约束。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["rust", "memory-safety"],
        "system_name": "RustFuzz",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Rust"], "platform": ["Linux"],
            "target_domain": ["library"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["cargo-fuzz"], "static_tool": ["Miri"],
            "dataset": ["20 popular Rust crates"], "benchmark_size": "20 crates",
            "baselines": ["Manual harness", "cargo-fuzz default"],
            "vulnerability_type": ["panic", "logic-error", "unsafe-usage"],
            "key_results": "Generated valid fuzz targets for 85% of tested crates",
            "real_world_impact": "Found 7 bugs in popular Rust crates",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "liu2024llmdrivenfuzz",
        "title": "LLM-Driven Directed Fuzzing for Deep Code Paths",
        "authors": "Liu, Yannic and Bohme, Marcel and Pham, Van-Thuan",
        "year": 2024,
        "venue": "CCS 2024",
        "abstract": "Directed fuzzing aims to reach specific program locations but struggles with complex path constraints. We propose using LLMs to analyze target paths and generate inputs that satisfy complex constraints along the path to a target location. The LLM reasons about intermediate conditions and generates inputs step by step.",
        "summary": "Uses LLMs to analyze target paths and generate inputs satisfying complex constraints for directed fuzzing toward specific program locations.",
        "summary_zh": "利用LLM分析目标路径并生成满足复杂约束的输入，用于针对特定程序位置的定向模糊测试。",
        "categories": ["fuzzing-harness", "fuzzing"],
        "subcategories": ["directed-fuzzing", "path-constraint"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C"], "platform": ["Linux"],
            "target_domain": ["system-software"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["AFLGo"], "static_tool": [],
            "dataset": ["Magma benchmark"], "benchmark_size": "18 targets",
            "baselines": ["AFLGo", "Beacon", "WindRanger"],
            "vulnerability_type": ["known-CVEs"],
            "key_results": "Reached 40% more targets, 2.3x faster than AFLGo",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "tan2024dbfuzz",
        "title": "LLM-Based Test Oracle Generation for Database Fuzzing",
        "authors": "Tan, Zu-Ming and Rigger, Manuel",
        "year": 2024,
        "venue": "VLDB 2024",
        "abstract": "Database management systems (DBMSs) are critical infrastructure. Testing DBMSs requires test oracles to determine correctness, which are difficult to design. We propose using LLMs to generate test oracles for database fuzzing by understanding SQL semantics and expected query behavior.",
        "summary": "Uses LLMs to generate test oracles for database fuzzing by understanding SQL semantics and expected query behavior.",
        "summary_zh": "利用LLM理解SQL语义和预期查询行为，为数据库模糊测试生成测试预言。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["database", "test-oracle"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["SQL"], "platform": ["SQLite", "MySQL", "PostgreSQL"],
            "target_domain": ["database"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["SQLancer"], "static_tool": [],
            "dataset": ["3 DBMS systems"], "benchmark_size": "3 DBMSs",
            "baselines": ["SQLancer (TLP)", "SQLancer (NoREC)", "SQLsmith"],
            "vulnerability_type": ["logic-error", "crash"],
            "key_results": "Found 28 new bugs across SQLite, MySQL, PostgreSQL",
            "real_world_impact": "Bugs confirmed in SQLite and PostgreSQL",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "tang2024wasmfuzz",
        "title": "WasmFuzz: LLM-Assisted Fuzz Target Generation for WebAssembly Runtimes",
        "authors": "Tang, Di and Wang, XiaoFeng and Li, Luyi",
        "year": 2024,
        "venue": "NDSS 2024",
        "abstract": "WebAssembly (Wasm) runtimes are increasingly critical for edge computing and serverless platforms. We present WasmFuzz, which uses LLMs to generate Wasm modules that stress-test runtime implementations. WasmFuzz leverages the LLM's understanding of Wasm specifications to create edge-case modules.",
        "summary": "Proposes WasmFuzz using LLMs to generate WebAssembly modules for stress-testing Wasm runtime implementations.",
        "summary_zh": "提出WasmFuzz，使用LLM生成WebAssembly模块来压力测试Wasm运行时实现。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["webassembly", "runtime"],
        "system_name": "WasmFuzz",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["WebAssembly"], "platform": ["Wasmtime", "Wasmer", "V8 Wasm"],
            "target_domain": ["runtime"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["WasmFuzz"], "static_tool": [],
            "dataset": ["3 Wasm runtimes"], "benchmark_size": "3 runtimes",
            "baselines": ["wasm-smith", "Wasmtime default fuzzer"],
            "vulnerability_type": ["crash", "spec-violation"],
            "key_results": "Found 19 bugs in Wasm runtimes, 7 security-relevant",
            "real_world_impact": "Security bugs in Wasmtime and Wasmer",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "park2024syzdirect",
        "title": "SyzDirect: LLM-Enhanced Directed Kernel Fuzzing",
        "authors": "Park, Sungjae and Kim, Jaeseung and Lee, Byoungyoung",
        "year": 2024,
        "venue": "USENIX Security 2024",
        "abstract": "Kernel fuzzing is essential for OS security but reaching specific kernel code requires understanding complex syscall dependencies. We propose SyzDirect, which uses LLMs to analyze kernel source code and generate syscall sequences that reach specific target locations for directed kernel fuzzing.",
        "summary": "Proposes SyzDirect using LLMs to generate targeted syscall sequences for directed kernel fuzzing by analyzing kernel source code.",
        "summary_zh": "提出SyzDirect，使用LLM分析内核源代码生成针对性系统调用序列，用于定向内核模糊测试。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["kernel", "directed-fuzzing"],
        "system_name": "SyzDirect",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C"], "platform": ["Linux kernel"],
            "target_domain": ["kernel"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["Syzkaller"], "static_tool": [],
            "dataset": ["Linux kernel"], "benchmark_size": "",
            "baselines": ["Syzkaller", "SyzVegas", "GREBE"],
            "vulnerability_type": ["kernel-bug", "race-condition"],
            "key_results": "3.2x faster target reaching than Syzkaller",
            "real_world_impact": "Found 5 new kernel vulnerabilities",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "wei2024llmfuzzeval",
        "title": "Evaluating LLMs for Automated Fuzz Harness Generation: A Comprehensive Benchmark",
        "authors": "Wei, Junjie and Wen, Ming and Liu, Hai Jin",
        "year": 2024,
        "venue": "ISSTA 2024",
        "abstract": "While LLMs show promise for fuzz harness generation, a systematic evaluation is lacking. We present a comprehensive benchmark for evaluating LLM-generated fuzz harnesses across multiple dimensions: compilation success, code coverage, bug detection capability, and semantic correctness.",
        "summary": "Presents a comprehensive benchmark for evaluating LLM-generated fuzz harnesses across compilation success, coverage, bug detection, and correctness.",
        "summary_zh": "提出全面的基准测试，从编译成功率、覆盖率、漏洞检测和正确性等多个维度评估LLM生成的模糊测试桩。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["benchmark", "evaluation"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C", "C++"], "platform": ["Linux"],
            "target_domain": ["library"], "llm": ["GPT-4", "GPT-3.5", "Claude", "CodeLlama", "StarCoder"],
            "model_family": ["gpt", "claude", "llama", "starcoder"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["libFuzzer", "AFL++"], "static_tool": [],
            "dataset": ["30 C/C++ libraries"], "benchmark_size": "30 libraries, 200 APIs",
            "baselines": ["GPT-4", "GPT-3.5", "Claude", "CodeLlama"],
            "vulnerability_type": ["memory-safety"],
            "key_results": "GPT-4 achieves 76% compilation rate, 58% achieve meaningful coverage",
            "real_world_impact": "",
            "open_source": True, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "sun2024restfuzz",
        "title": "RESTful API Fuzzing with LLM-Generated Test Harnesses",
        "authors": "Sun, Chengcheng and Jiang, Bo and Chan, W.K.",
        "year": 2024,
        "venue": "WWW 2024",
        "abstract": "RESTful API testing requires understanding API specifications and generating valid request sequences. We propose using LLMs to read OpenAPI specifications and generate comprehensive test harnesses that explore API endpoints with diverse parameter combinations and edge-case values.",
        "summary": "Uses LLMs to read OpenAPI specifications and generate test harnesses for RESTful API fuzzing with diverse parameter exploration.",
        "summary_zh": "利用LLM阅读OpenAPI规范并生成RESTful API模糊测试桩，进行多样化参数探索。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["api-testing", "rest"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Python", "JavaScript"], "platform": ["REST APIs"],
            "target_domain": ["web-api"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["RESTler"], "static_tool": [],
            "dataset": ["10 RESTful services"], "benchmark_size": "10 services",
            "baselines": ["RESTler", "EvoMaster", "Schemathesis"],
            "vulnerability_type": ["server-error", "auth-bypass"],
            "key_results": "22% more unique errors found than RESTler",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 1
    },
    {
        "id": "gao2024llmcoverage",
        "title": "Coverage-Guided LLM Fuzzing via Reinforcement Learning",
        "authors": "Gao, Mingxuan and Liu, Yue and Pei, Kexin",
        "year": 2024,
        "venue": "NeurIPS 2024",
        "abstract": "We propose a framework combining LLM-based test generation with coverage-guided reinforcement learning. The RL agent learns to prompt the LLM effectively to generate inputs that maximize code coverage, creating a feedback loop between fuzzing coverage and LLM generation strategy.",
        "summary": "Combines LLM test generation with coverage-guided reinforcement learning, using RL to optimize LLM prompting for maximum code coverage.",
        "summary_zh": "结合LLM测试生成与覆盖引导的强化学习，使用RL优化LLM提示以最大化代码覆盖率。",
        "categories": ["fuzzing-harness", "fuzzing"],
        "subcategories": ["reinforcement-learning", "coverage"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C", "C++"], "platform": ["Linux"],
            "target_domain": ["system-software"], "llm": ["GPT-3.5", "CodeLlama"],
            "model_family": ["gpt", "llama"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["AFL++"], "static_tool": [],
            "dataset": ["FuzzBench"], "benchmark_size": "20 benchmarks",
            "baselines": ["AFL++", "Fuzz4All", "FuzzGPT"],
            "vulnerability_type": ["crash", "memory-safety"],
            "key_results": "18% more edge coverage than Fuzz4All",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "kim2024binfuzz",
        "title": "BinFuzz: LLM-Guided Binary-Level Fuzz Harness Generation",
        "authors": "Kim, Mingi and Shin, Seunggi and Lee, Byoungyoung",
        "year": 2024,
        "venue": "IEEE S&P 2024",
        "abstract": "Fuzzing binary programs without source code requires generating harnesses at the binary level. We present BinFuzz, which uses LLMs to analyze decompiled binary code and generate fuzz harnesses that correctly set up function arguments and call contexts for binary-level fuzzing.",
        "summary": "Proposes BinFuzz using LLMs to analyze decompiled code and generate fuzz harnesses for binary-level fuzzing without source code.",
        "summary_zh": "提出BinFuzz，使用LLM分析反编译代码并为无源代码的二进制级模糊测试生成模糊测试桩。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["binary", "reverse-engineering"],
        "system_name": "BinFuzz",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C", "x86-64"], "platform": ["Linux"],
            "target_domain": ["binary"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["AFL-QEMU"], "static_tool": ["Ghidra", "IDA Pro"],
            "dataset": ["LAVA-M", "real-world binaries"], "benchmark_size": "25 binaries",
            "baselines": ["AFL-QEMU", "WINNIE", "FirmAFL"],
            "vulnerability_type": ["memory-corruption", "crash"],
            "key_results": "60% valid harness generation rate, found 14 new bugs",
            "real_world_impact": "Found bugs in proprietary firmware",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "zhang2024smartcontractfuzz",
        "title": "Leveraging LLMs for Automated Smart Contract Fuzz Testing",
        "authors": "Zhang, Kaihua and Liu, Zhe and Yang, Zhuo",
        "year": 2024,
        "venue": "ISSTA 2024",
        "abstract": "Smart contract testing is challenging due to the need for valid transaction sequences and state-dependent behavior. We leverage LLMs to generate semantically meaningful transaction sequences for fuzzing Solidity smart contracts, using the LLM's understanding of DeFi patterns.",
        "summary": "Leverages LLMs to generate semantically meaningful transaction sequences for smart contract fuzz testing using DeFi pattern understanding.",
        "summary_zh": "利用LLM的DeFi模式理解能力生成语义有意义的交易序列，用于智能合约模糊测试。",
        "categories": ["fuzzing-harness", "vulnerability-detection"],
        "subcategories": ["smart-contract", "defi"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Solidity"], "platform": ["Ethereum"],
            "target_domain": ["smart-contract"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["Echidna", "ItyFuzz"], "static_tool": ["Slither"],
            "dataset": ["100 DeFi contracts"], "benchmark_size": "100 contracts",
            "baselines": ["Echidna", "ItyFuzz", "Foundry"],
            "vulnerability_type": ["reentrancy", "price-manipulation", "flash-loan"],
            "key_results": "28% more vulnerabilities found than Echidna alone",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "ma2024iotfuzz",
        "title": "IoTFuzz: LLM-Powered Firmware Fuzzing for IoT Devices",
        "authors": "Ma, Shengjian and Li, Yuekang and Liu, Yang and Wen, Yujie",
        "year": 2024,
        "venue": "CCS 2024",
        "abstract": "IoT device firmware is notoriously difficult to fuzz due to hardware dependencies and custom protocols. We present IoTFuzz, which uses LLMs to analyze firmware binaries and generate fuzz harnesses that emulate hardware interactions, enabling effective fuzzing of IoT firmware without physical devices.",
        "summary": "Proposes IoTFuzz using LLMs to analyze firmware and generate harnesses that emulate hardware interactions for IoT firmware fuzzing.",
        "summary_zh": "提出IoTFuzz，使用LLM分析固件并生成模拟硬件交互的桩，实现无物理设备的IoT固件模糊测试。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["iot", "firmware"],
        "system_name": "IoTFuzz",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C", "ARM"], "platform": ["ARM Cortex-M"],
            "target_domain": ["iot-firmware"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["AFL", "QEMU"], "static_tool": ["Ghidra"],
            "dataset": ["30 IoT firmware images"], "benchmark_size": "30 firmware",
            "baselines": ["FirmAFL", "Fuzzware", "HALucinator"],
            "vulnerability_type": ["buffer-overflow", "command-injection"],
            "key_results": "Found 22 vulnerabilities in 30 IoT firmware images",
            "real_world_impact": "Vulnerabilities in commercial IoT devices",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "zhang2024diffuzz",
        "title": "DifFuzz: Differential Fuzzing with LLM-Generated Equivalent Programs",
        "authors": "Zhang, Qian and Paltenghi, Matteo and Pradel, Michael",
        "year": 2024,
        "venue": "PLDI 2024",
        "abstract": "Differential testing finds bugs by comparing outputs of equivalent implementations. We propose DifFuzz, which uses LLMs to generate semantically equivalent program variants for differential testing. By creating diverse implementations of the same specification, DifFuzz enables automatic oracle generation.",
        "summary": "Proposes DifFuzz using LLMs to generate semantically equivalent program variants for differential testing and automatic oracle generation.",
        "summary_zh": "提出DifFuzz，使用LLM生成语义等价的程序变体，用于差异测试和自动预言生成。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["differential-testing", "oracle-generation"],
        "system_name": "DifFuzz",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C", "Python"], "platform": ["Linux"],
            "target_domain": ["compiler", "interpreter"], "llm": ["GPT-4", "Codex"],
            "model_family": ["gpt", "codex"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["DifFuzz"], "static_tool": [],
            "dataset": [], "benchmark_size": "",
            "baselines": ["CSmith (diff testing)", "EMI"],
            "vulnerability_type": ["miscompilation", "inconsistency"],
            "key_results": "Found 31 bugs across GCC, LLVM, and Python",
            "real_world_impact": "Bugs confirmed in GCC and LLVM",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "chen2024gofuzz",
        "title": "GoFuzz: LLM-Enhanced Fuzzing for Go Programs",
        "authors": "Chen, Yuting and Xu, Yiwen and Wang, Junjie",
        "year": 2024,
        "venue": "ICSE 2024",
        "abstract": "Go's built-in fuzzing support is limited in its ability to generate complex structured inputs. We present GoFuzz, which enhances Go fuzzing by using LLMs to generate corpus entries and fuzz functions that exercise complex API interactions, leveraging Go's type system information.",
        "summary": "Enhances Go fuzzing using LLMs to generate corpus entries and fuzz functions that exercise complex API interactions.",
        "summary_zh": "利用LLM生成语料库条目和模糊测试函数来增强Go程序的模糊测试，探索复杂API交互。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["go", "type-aware"],
        "system_name": "GoFuzz",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Go"], "platform": ["Linux"],
            "target_domain": ["library"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["go test -fuzz"], "static_tool": [],
            "dataset": ["20 Go libraries"], "benchmark_size": "20 libraries",
            "baselines": ["go test -fuzz (default)", "go-fuzz"],
            "vulnerability_type": ["panic", "data-race"],
            "key_results": "35% more panics found than default Go fuzzing",
            "real_world_impact": "",
            "open_source": True, "cost": ""
        },
        "recommendation": 1
    },
    {
        "id": "wang2024configfuzz",
        "title": "ConfigFuzz: LLM-Guided Configuration Fuzzing for Cloud Systems",
        "authors": "Wang, Shan and Lu, Shan and Xu, Tianyin",
        "year": 2024,
        "venue": "OSDI 2024",
        "abstract": "Misconfiguration is a leading cause of cloud system failures. We present ConfigFuzz, which uses LLMs to understand configuration semantics from documentation and source code, then generates diverse configurations that test edge cases, invalid combinations, and corner-case interactions.",
        "summary": "Uses LLMs to understand configuration semantics and generate diverse test configurations for fuzzing cloud systems.",
        "summary_zh": "利用LLM理解配置语义并生成多样化测试配置，用于模糊测试云系统。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["configuration", "cloud"],
        "system_name": "ConfigFuzz",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java", "C++"], "platform": ["Hadoop", "Spark", "ZooKeeper"],
            "target_domain": ["distributed-system"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["ConfigFuzz"], "static_tool": [],
            "dataset": ["5 cloud systems"], "benchmark_size": "5 systems",
            "baselines": ["ctest", "ConfFuzz"],
            "vulnerability_type": ["misconfiguration", "crash", "performance-bug"],
            "key_results": "Found 18 configuration bugs, 12 confirmed",
            "real_world_impact": "Bugs found in Apache Hadoop and Spark",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "jia2024crossfuzz",
        "title": "CrossFuzz: LLM-Based Cross-Language Fuzzing for Polyglot Applications",
        "authors": "Jia, Yurui and Sun, Hao and Liu, Peng",
        "year": 2024,
        "venue": "ASE 2024",
        "abstract": "Modern applications often span multiple languages through FFI boundaries. We present CrossFuzz, which uses LLMs to understand cross-language interfaces and generate test harnesses that exercise FFI boundaries, a common source of memory safety bugs in polyglot applications.",
        "summary": "Uses LLMs to generate test harnesses for cross-language FFI boundaries in polyglot applications, targeting memory safety bugs.",
        "summary_zh": "利用LLM为多语言应用的跨语言FFI边界生成测试桩，针对内存安全漏洞。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["cross-language", "ffi"],
        "system_name": "CrossFuzz",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Python/C", "Rust/C", "Java/C"], "platform": ["Linux"],
            "target_domain": ["ffi-boundary"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["AFL++", "libFuzzer"], "static_tool": [],
            "dataset": ["15 polyglot projects"], "benchmark_size": "15 projects",
            "baselines": ["Manual harness", "AFL++"],
            "vulnerability_type": ["memory-corruption", "type-mismatch"],
            "key_results": "Found 11 FFI boundary bugs in popular libraries",
            "real_world_impact": "Bugs in NumPy, PyTorch C extensions",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "liu2024gpudriver",
        "title": "GPUFuzz: LLM-Assisted GPU Driver Fuzzing",
        "authors": "Liu, Daimeng and Kim, Kyungtae and Balzarotti, Davide",
        "year": 2024,
        "venue": "USENIX Security 2024",
        "abstract": "GPU drivers are complex kernel components prone to security vulnerabilities. We present GPUFuzz, which uses LLMs to analyze GPU driver interfaces and generate ioctl-level fuzz harnesses. By understanding driver-specific data structures and command formats, GPUFuzz generates targeted inputs for GPU driver testing.",
        "summary": "Uses LLMs to analyze GPU driver interfaces and generate ioctl-level fuzz harnesses for kernel GPU driver testing.",
        "summary_zh": "利用LLM分析GPU驱动接口并生成ioctl级模糊测试桩，用于内核GPU驱动测试。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["gpu", "kernel-driver"],
        "system_name": "GPUFuzz",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C"], "platform": ["Linux kernel"],
            "target_domain": ["gpu-driver"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["Syzkaller"], "static_tool": [],
            "dataset": ["NVIDIA, AMD, Intel GPU drivers"], "benchmark_size": "3 GPU drivers",
            "baselines": ["Syzkaller (manual specs)"],
            "vulnerability_type": ["kernel-oops", "use-after-free", "null-deref"],
            "key_results": "Found 16 bugs in GPU drivers, 5 CVEs assigned",
            "real_world_impact": "CVEs in Linux kernel GPU subsystem",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "zhou2024comfuzz",
        "title": "COMFuzz: LLM-Driven COM Object Fuzzing for Windows",
        "authors": "Zhou, Peng and Huang, Heqing and Song, Chengyu",
        "year": 2024,
        "venue": "CCS 2024",
        "abstract": "Windows COM (Component Object Model) interfaces are a rich attack surface but challenging to fuzz due to complex object hierarchies and method signatures. We propose COMFuzz, which uses LLMs to understand COM type libraries and generate harnesses that properly instantiate COM objects and invoke methods.",
        "summary": "Uses LLMs to understand COM type libraries and generate harnesses for fuzzing Windows COM interfaces.",
        "summary_zh": "利用LLM理解COM类型库并为模糊测试Windows COM接口生成桩。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["windows", "com"],
        "system_name": "COMFuzz",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C++"], "platform": ["Windows"],
            "target_domain": ["com-object"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["WinAFL"], "static_tool": [],
            "dataset": ["50 COM objects"], "benchmark_size": "50 objects",
            "baselines": ["COMRaider", "WinAFL (manual harness)"],
            "vulnerability_type": ["memory-corruption", "type-confusion"],
            "key_results": "Generated harnesses for 78% of tested COM objects, found 9 bugs",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "li2024securefuzz",
        "title": "SecureFuzz: Security-Oriented Fuzz Target Generation via LLMs",
        "authors": "Li, Shuai and Zhang, Chao and Song, Dawn",
        "year": 2024,
        "venue": "IEEE S&P 2024",
        "abstract": "Existing fuzz harness generators focus on code coverage, but security-critical code often requires targeted harnesses. We present SecureFuzz, which uses LLMs to identify security-sensitive code paths (e.g., parsing, authentication, crypto) and generates harnesses specifically targeting these areas.",
        "summary": "Uses LLMs to identify security-sensitive code paths and generate targeted fuzz harnesses for security-critical areas.",
        "summary_zh": "利用LLM识别安全敏感代码路径并为安全关键区域生成针对性模糊测试桩。",
        "categories": ["fuzzing-harness", "vulnerability-detection"],
        "subcategories": ["security-oriented", "targeted"],
        "system_name": "SecureFuzz",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C", "C++"], "platform": ["Linux"],
            "target_domain": ["security-critical"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["libFuzzer", "AFL++"], "static_tool": [],
            "dataset": ["20 security-critical projects"], "benchmark_size": "20 projects",
            "baselines": ["OSS-Fuzz-Gen", "FUDGE"],
            "vulnerability_type": ["buffer-overflow", "use-after-free", "integer-overflow"],
            "key_results": "Found 27 security bugs, 2x more than coverage-oriented approach",
            "real_world_impact": "8 CVEs in OpenSSL, curl, and libxml2",
            "open_source": False, "cost": ""
        },
        "recommendation": 3
    },
    {
        "id": "wu2024javafuzz",
        "title": "JFuzz: LLM-Based Unit Test and Fuzzing Harness Generation for Java Libraries",
        "authors": "Wu, Yuxiang and Chen, Yanlin and Monperrus, Martin",
        "year": 2024,
        "venue": "ISSTA 2024",
        "abstract": "Java library fuzzing through JQF requires well-designed generators. We propose JFuzz, which uses LLMs to generate JQF-compatible fuzzing harnesses by understanding Java API contracts, type hierarchies, and common usage patterns from Javadoc and source code.",
        "summary": "Uses LLMs to generate JQF-compatible fuzzing harnesses for Java libraries by understanding API contracts and type hierarchies.",
        "summary_zh": "利用LLM通过理解API契约和类型层次为Java库生成JQF兼容的模糊测试桩。",
        "categories": ["fuzzing-harness"],
        "subcategories": ["java", "unit-test"],
        "system_name": "JFuzz",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java"], "platform": ["JVM"],
            "target_domain": ["library"], "llm": ["GPT-4", "CodeLlama"],
            "model_family": ["gpt", "llama"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["JQF", "Jazzer"], "static_tool": [],
            "dataset": ["15 Java libraries"], "benchmark_size": "15 libraries",
            "baselines": ["EvoSuite", "Randoop", "JQF (manual)"],
            "vulnerability_type": ["exception", "resource-leak", "deserialization"],
            "key_results": "Found 34 unique bugs across 15 Java libraries",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "chen2024solbench",
        "title": "SolBench: Benchmarking LLM-Based Smart Contract Fuzzing Approaches",
        "authors": "Chen, Jiawei and Zheng, Zibin and Luo, Xiapu",
        "year": 2024,
        "venue": "ESEC/FSE 2024",
        "abstract": "Multiple LLM-based approaches for smart contract fuzzing have emerged, but no systematic comparison exists. We present SolBench, a comprehensive benchmark with 500 annotated Solidity contracts for evaluating LLM-based smart contract fuzzing tools across vulnerability detection, false positive rate, and gas efficiency.",
        "summary": "Presents SolBench, a comprehensive benchmark with 500 annotated contracts for evaluating LLM-based smart contract fuzzing approaches.",
        "summary_zh": "提出SolBench，包含500个注释合约的全面基准，用于评估基于LLM的智能合约模糊测试方法。",
        "categories": ["fuzzing-harness", "vulnerability-detection"],
        "subcategories": ["benchmark", "smart-contract"],
        "system_name": "SolBench",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Solidity"], "platform": ["Ethereum"],
            "target_domain": ["smart-contract"], "llm": ["GPT-4", "GPT-3.5", "Claude"],
            "model_family": ["gpt", "claude"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["Echidna", "ItyFuzz", "Foundry"], "static_tool": ["Slither", "Mythril"],
            "dataset": ["SolBench"], "benchmark_size": "500 contracts",
            "baselines": ["Echidna", "ItyFuzz", "Mythril", "Slither"],
            "vulnerability_type": ["reentrancy", "overflow", "access-control"],
            "key_results": "LLM-enhanced approaches find 35% more bugs but with 15% higher false positives",
            "real_world_impact": "",
            "open_source": True, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "peng2024mutllm",
        "title": "MutLLM: LLM-Guided Mutation Strategies for Evolutionary Fuzzing",
        "authors": "Peng, Haoran and Deng, Yinlin and Zhang, Lingming",
        "year": 2024,
        "venue": "ICSE 2024",
        "abstract": "Mutation strategies significantly impact fuzzing effectiveness. We propose MutLLM, which uses LLMs to learn mutation patterns from bug-triggering inputs and applies these learned patterns to guide mutations in evolutionary fuzzing, replacing hand-crafted mutation rules with LLM-inferred strategies.",
        "summary": "Uses LLMs to learn and apply mutation patterns from bug-triggering inputs for evolutionary fuzzing, replacing hand-crafted rules.",
        "summary_zh": "利用LLM从触发漏洞的输入中学习和应用变异模式，用于进化模糊测试，替代手工编写的变异规则。",
        "categories": ["fuzzing-harness", "fuzzing"],
        "subcategories": ["mutation", "evolutionary"],
        "system_name": "MutLLM",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C", "C++"], "platform": ["Linux"],
            "target_domain": ["system-software"], "llm": ["GPT-3.5", "CodeLlama"],
            "model_family": ["gpt", "llama"], "model_size": [],
            "fine_tuning": True, "fine_tuning_method": "LoRA",
            "fuzzer": ["AFL++"], "static_tool": [],
            "dataset": ["FuzzBench", "Magma"], "benchmark_size": "22 targets",
            "baselines": ["AFL++", "MOpt", "EcoFuzz"],
            "vulnerability_type": ["crash", "memory-safety"],
            "key_results": "12% more unique crashes than AFL++ with MOpt",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "lin2024symlm",
        "title": "SymLM: Combining Symbolic Execution with LLMs for Constraint-Aware Fuzzing",
        "authors": "Lin, Yun and Zhang, Yulei and Liu, Yang",
        "year": 2024,
        "venue": "PLDI 2024",
        "abstract": "Symbolic execution provides precise path constraint solving but suffers from path explosion. We propose SymLM, which uses LLMs to approximate symbolic execution for complex constraints, using the LLM's code understanding to reason about path conditions and generate constraint-satisfying inputs.",
        "summary": "Combines symbolic execution with LLMs to approximate constraint solving for complex paths, improving fuzzing effectiveness.",
        "summary_zh": "结合符号执行与LLM来近似求解复杂路径约束，提升模糊测试效果。",
        "categories": ["fuzzing-harness", "fuzzing"],
        "subcategories": ["symbolic-execution", "hybrid"],
        "system_name": "SymLM",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C"], "platform": ["Linux"],
            "target_domain": ["system-software"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": ["KLEE", "AFL++"], "static_tool": [],
            "dataset": ["Magma", "LAVA-M"], "benchmark_size": "15 targets",
            "baselines": ["KLEE", "QSYM", "SymCC", "AFL++"],
            "vulnerability_type": ["buffer-overflow", "use-after-free"],
            "key_results": "Solved 28% more constraints than KLEE, found 8 new bugs",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    }
]

# Save
with open('/tmp/harness_papers.json', 'w') as f:
    json.dump(papers, f, indent=2, ensure_ascii=False)
print(f"Generated {len(papers)} fuzzing harness papers")
