#!/usr/bin/env python3
"""Generate LLM for patching/program repair papers."""
import json

papers = [
    {
        "id": "xia2023chatrepair",
        "title": "Keep the Conversation Going: Fixing 162 out of 337 bugs for $0.42 each using ChatGPT",
        "authors": "Xia, Chunqiu Steven and Zhang, Lingming",
        "year": 2023,
        "venue": "arXiv preprint",
        "abstract": "Automated program repair (APR) aims to fix software bugs automatically. We present ChatRepair, which uses conversational repair with ChatGPT. By providing failing test information and iteratively refining patches through multi-turn conversation, ChatRepair achieves state-of-the-art repair performance at minimal cost.",
        "summary": "Proposes ChatRepair using multi-turn ChatGPT conversation for automated program repair, fixing 162 of 337 bugs at $0.42 per bug.",
        "summary_zh": "提出ChatRepair，利用多轮ChatGPT对话进行自动程序修复，以每个漏洞0.42美元的成本修复了337个漏洞中的162个。",
        "categories": ["patching"],
        "subcategories": ["conversational", "java"],
        "system_name": "ChatRepair",
        "paperUrl": "https://arxiv.org/abs/2304.00385",
        "codeUrl": "",
        "experiment": {
            "language": ["Java"], "platform": ["Defects4J"],
            "target_domain": ["bug-fix"], "llm": ["ChatGPT", "GPT-3.5"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["Defects4J v1.2", "Defects4J v2.0"], "benchmark_size": "337 bugs",
            "baselines": ["AlphaRepair", "CURE", "RewardRepair", "Codex"],
            "vulnerability_type": ["logic-error", "null-pointer", "off-by-one"],
            "key_results": "Fixed 162/337 bugs on Defects4J, SOTA at $0.42/bug average cost",
            "real_world_impact": "Demonstrates cost-effective automated repair",
            "open_source": False, "cost": "$0.42 per bug"
        },
        "recommendation": 3
    },
    {
        "id": "xia2024apr",
        "title": "Automated Program Repair in the Era of Large Pre-trained Language Models",
        "authors": "Xia, Chunqiu Steven and Wei, Yuxiang and Zhang, Lingming",
        "year": 2024,
        "venue": "ICSE 2024",
        "abstract": "We conduct the first extensive study on LLM-based automated program repair. We evaluate multiple LLMs including Codex, ChatGPT, GPT-4, InCoder, and CodeGen on standard APR benchmarks. Our study reveals that LLMs significantly outperform prior APR tools and identifies key factors affecting repair performance.",
        "summary": "Extensive study evaluating LLMs on automated program repair benchmarks, showing LLMs significantly outperform prior APR tools.",
        "summary_zh": "广泛研究评估LLM在自动程序修复基准上的表现，表明LLM显著优于之前的APR工具。",
        "categories": ["patching"],
        "subcategories": ["empirical-study", "benchmark"],
        "system_name": "",
        "paperUrl": "https://arxiv.org/abs/2304.11006",
        "codeUrl": "",
        "experiment": {
            "language": ["Java", "Python"], "platform": [],
            "target_domain": ["bug-fix"], "llm": ["Codex", "ChatGPT", "GPT-4", "InCoder", "CodeGen"],
            "model_family": ["gpt", "incoder", "codegen"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["Defects4J", "QuixBugs", "BugsInPy"], "benchmark_size": "835 bugs",
            "baselines": ["AlphaRepair", "CURE", "TBar", "SimFix"],
            "vulnerability_type": ["logic-error"],
            "key_results": "GPT-4 fixes 55% more bugs than best prior APR tool",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 3
    },
    {
        "id": "wei2023copiloting",
        "title": "Copiloting the Copilots: Fusing Large Language Models with Completion Engines for Automated Program Repair",
        "authors": "Wei, Yuxiang and Xia, Chunqiu Steven and Zhang, Lingming",
        "year": 2023,
        "venue": "ESEC/FSE 2023",
        "abstract": "LLMs generate plausible patches but sometimes produce syntactically invalid or type-incorrect code. We propose Repilot, which fuses LLMs with completion engines to ensure generated patches are syntactically valid and type-correct, combining the creativity of LLMs with the precision of program analysis.",
        "summary": "Proposes Repilot fusing LLMs with completion engines to generate syntactically valid and type-correct patches for automated program repair.",
        "summary_zh": "提出Repilot，融合LLM与代码补全引擎，生成语法有效且类型正确的补丁用于自动程序修复。",
        "categories": ["patching"],
        "subcategories": ["completion-engine", "type-aware"],
        "system_name": "Repilot",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java"], "platform": [],
            "target_domain": ["bug-fix"], "llm": ["Codex"],
            "model_family": ["codex"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["Defects4J v1.2", "Defects4J v2.0"], "benchmark_size": "337 bugs",
            "baselines": ["AlphaRepair", "Codex", "CURE"],
            "vulnerability_type": ["logic-error"],
            "key_results": "Fixed 24% more bugs than Codex alone",
            "real_world_impact": "",
            "open_source": True, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "fu2022vulrepair",
        "title": "VulRepair: A T5-Based Automated Software Vulnerability Repair",
        "authors": "Fu, Michael and Tantithamthavorn, Chakkrit",
        "year": 2022,
        "venue": "ESEC/FSE 2022",
        "abstract": "Security vulnerabilities require timely patches, but manual repair is slow. We present VulRepair, a T5-based model fine-tuned specifically for vulnerability repair. By training on a curated dataset of vulnerability-patch pairs from real-world CVEs, VulRepair learns to generate security patches.",
        "summary": "Proposes VulRepair, a T5-based model fine-tuned on CVE-patch pairs for automated vulnerability repair, achieving 44% exact-match accuracy.",
        "summary_zh": "提出VulRepair，基于T5模型在CVE补丁对上微调用于自动漏洞修复，实现44%的精确匹配准确率。",
        "categories": ["patching", "vulnerability-detection"],
        "subcategories": ["vulnerability-repair", "fine-tuning"],
        "system_name": "VulRepair",
        "paperUrl": "",
        "codeUrl": "https://github.com/awsm-research/VulRepair",
        "experiment": {
            "language": ["C", "C++"], "platform": [],
            "target_domain": ["vulnerability-repair"], "llm": ["T5"],
            "model_family": ["t5"], "model_size": ["220M"],
            "fine_tuning": True, "fine_tuning_method": "full",
            "fuzzer": [], "static_tool": [],
            "dataset": ["CVEFixes", "Big-Vul"], "benchmark_size": "8482 vulnerability-patch pairs",
            "baselines": ["CodeBERT", "GraphCodeBERT", "SequenceR"],
            "vulnerability_type": ["CWE-119", "CWE-20", "CWE-125"],
            "key_results": "44% exact-match accuracy on vulnerability repair",
            "real_world_impact": "",
            "open_source": True, "cost": ""
        },
        "recommendation": 3
    },
    {
        "id": "huang2024srepair",
        "title": "SRepair: Semantic-Level Automated Program Repair via Large Language Models",
        "authors": "Huang, Yuntong and Xia, Chunqiu Steven and Zhang, Lingming",
        "year": 2024,
        "venue": "ASE 2024",
        "abstract": "Existing APR approaches operate at the syntactic level, limiting their ability to fix complex bugs requiring semantic understanding. We present SRepair, which leverages LLMs for semantic-level program repair. SRepair uses semantic analysis to understand bug root causes before prompting the LLM for fixes.",
        "summary": "Proposes SRepair for semantic-level program repair using LLMs with root cause analysis, fixing complex multi-location bugs.",
        "summary_zh": "提出SRepair，利用LLM进行语义级程序修复，结合根因分析修复复杂的多位置漏洞。",
        "categories": ["patching"],
        "subcategories": ["semantic", "root-cause"],
        "system_name": "SRepair",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java"], "platform": [],
            "target_domain": ["bug-fix"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["Defects4J"], "benchmark_size": "395 bugs",
            "baselines": ["ChatRepair", "AlphaRepair", "CURE"],
            "vulnerability_type": ["logic-error", "semantic-bug"],
            "key_results": "Fixed 178/395 bugs, 10% more than ChatRepair",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "ye2024iter",
        "title": "ITER: Iterative Neural Repair for Multi-Location Bugs",
        "authors": "Ye, He and Monperrus, Martin",
        "year": 2024,
        "venue": "ICSE 2024",
        "abstract": "Multi-location bugs require coordinated changes across multiple code locations, which is challenging for existing APR tools. We present ITER, an iterative repair approach that uses LLMs to fix multi-location bugs one location at a time, using test feedback to guide subsequent repairs.",
        "summary": "Proposes ITER for iterative repair of multi-location bugs using LLMs with test feedback to guide sequential fixes.",
        "summary_zh": "提出ITER，利用LLM通过测试反馈引导顺序修复，迭代修复多位置漏洞。",
        "categories": ["patching"],
        "subcategories": ["multi-location", "iterative"],
        "system_name": "ITER",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java", "Python"], "platform": [],
            "target_domain": ["bug-fix"], "llm": ["GPT-4", "CodeLlama"],
            "model_family": ["gpt", "llama"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["Defects4J", "BugsInPy"], "benchmark_size": "300 multi-location bugs",
            "baselines": ["ChatRepair", "CURE", "Codex"],
            "vulnerability_type": ["multi-location-bug"],
            "key_results": "Fixed 45% of multi-location bugs vs 18% for single-shot approaches",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "silva2024repairllama",
        "title": "RepairLlama: Efficient Representation Learning for Fine-Tuned Code Repair Models",
        "authors": "Silva, Andre and Monperrus, Martin",
        "year": 2024,
        "venue": "arXiv preprint",
        "abstract": "While large commercial LLMs show strong repair capabilities, open-source alternatives lag behind. We present RepairLlama, a fine-tuned Llama model specifically for program repair. Through parameter-efficient fine-tuning on curated bug-fix datasets, RepairLlama achieves competitive performance with GPT-3.5.",
        "summary": "Fine-tunes Llama for program repair using LoRA, achieving competitive performance with GPT-3.5 at much lower cost.",
        "summary_zh": "使用LoRA微调Llama用于程序修复，以更低成本达到与GPT-3.5相当的性能。",
        "categories": ["patching"],
        "subcategories": ["fine-tuning", "open-source"],
        "system_name": "RepairLlama",
        "paperUrl": "",
        "codeUrl": "https://github.com/ASSERT-KTH/RepairLlama",
        "experiment": {
            "language": ["Java"], "platform": [],
            "target_domain": ["bug-fix"], "llm": ["Llama-2"],
            "model_family": ["llama"], "model_size": ["13B"],
            "fine_tuning": True, "fine_tuning_method": "LoRA",
            "fuzzer": [], "static_tool": [],
            "dataset": ["Defects4J", "MegaDiff"], "benchmark_size": "337 bugs",
            "baselines": ["GPT-3.5", "Codex", "InCoder", "AlphaRepair"],
            "vulnerability_type": ["logic-error"],
            "key_results": "Matches GPT-3.5 on Defects4J at 10x lower cost",
            "real_world_impact": "",
            "open_source": True, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "jin2023inferfix",
        "title": "InferFix: End-to-End Program Repair with LLMs over Retrieval-Augmented Prompts",
        "authors": "Jin, Matthew and Shahriar, Syed and Tufano, Michele and Shi, Xin and Lu, Shuai and Sundaresan, Neel and Svyatkovskiy, Alexey",
        "year": 2023,
        "venue": "ESEC/FSE 2023",
        "abstract": "We present InferFix, an end-to-end program repair system that combines static analysis with retrieval-augmented LLM generation. InferFix uses Infer's static analyzer to identify bugs, retrieves similar bug-fix pairs, and prompts an LLM with relevant context to generate patches.",
        "summary": "Proposes InferFix combining Infer static analysis with retrieval-augmented LLM patch generation for end-to-end program repair.",
        "summary_zh": "提出InferFix，结合Infer静态分析与检索增强的LLM补丁生成，实现端到端程序修复。",
        "categories": ["patching", "vulnerability-detection"],
        "subcategories": ["static-analysis", "retrieval-augmented"],
        "system_name": "InferFix",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java", "C"], "platform": [],
            "target_domain": ["bug-fix"], "llm": ["Codex", "GPT-3.5"],
            "model_family": ["codex", "gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": ["Infer"],
            "dataset": ["InferredBugs"], "benchmark_size": "10000+ Infer warnings",
            "baselines": ["Codex (zero-shot)", "CodeBERT"],
            "vulnerability_type": ["null-pointer", "resource-leak", "thread-safety"],
            "key_results": "65% of generated patches pass validation, 40% exact match",
            "real_world_impact": "Deployed in Microsoft developer workflow",
            "open_source": False, "cost": ""
        },
        "recommendation": 3
    },
    {
        "id": "zhang2024autocoderover",
        "title": "AutoCodeRover: Autonomous Program Improvement via LLM Agents",
        "authors": "Zhang, Yuntong and Ruan, Haifeng and Fan, Zhiyu and Roychoudhury, Abhik",
        "year": 2024,
        "venue": "ISSTA 2024",
        "abstract": "We present AutoCodeRover, an autonomous LLM agent for program improvement. Unlike prior approaches that focus on single-hunk patches, AutoCodeRover navigates codebases autonomously, identifies relevant code contexts, and generates multi-file patches using an iterative agent-based approach.",
        "summary": "Proposes AutoCodeRover, an autonomous LLM agent that navigates codebases and generates multi-file patches for program improvement.",
        "summary_zh": "提出AutoCodeRover，一个自主导航代码库并生成多文件补丁的LLM代理，用于程序改进。",
        "categories": ["patching"],
        "subcategories": ["agent", "multi-file"],
        "system_name": "AutoCodeRover",
        "paperUrl": "https://arxiv.org/abs/2404.05427",
        "codeUrl": "https://github.com/nus-apr/auto-code-rover",
        "experiment": {
            "language": ["Python"], "platform": [],
            "target_domain": ["bug-fix"], "llm": ["GPT-4", "Claude"],
            "model_family": ["gpt", "claude"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["SWE-bench"], "benchmark_size": "2294 GitHub issues",
            "baselines": ["SWE-agent", "Devin", "RAG baseline"],
            "vulnerability_type": ["github-issue"],
            "key_results": "Resolved 22% of SWE-bench issues, SOTA at time of publication",
            "real_world_impact": "Resolves real GitHub issues autonomously",
            "open_source": True, "cost": ""
        },
        "recommendation": 3
    },
    {
        "id": "jimenez2024swebench",
        "title": "SWE-bench: Can Language Models Resolve Real-World GitHub Issues?",
        "authors": "Jimenez, Carlos E. and Yang, John and Wettig, Alexander and Yao, Shunyu and Pei, Kexin and Press, Ofir and Narasimhan, Karthik",
        "year": 2024,
        "venue": "ICLR 2024",
        "abstract": "We introduce SWE-bench, a benchmark for evaluating LLMs on real-world software engineering tasks. SWE-bench collects 2,294 task instances from 12 popular Python repositories, where each instance requires the model to resolve a GitHub issue by generating a patch.",
        "summary": "Introduces SWE-bench, a benchmark of 2,294 real GitHub issues for evaluating LLMs on software engineering and patch generation.",
        "summary_zh": "引入SWE-bench，包含2294个真实GitHub问题的基准，用于评估LLM在软件工程和补丁生成上的能力。",
        "categories": ["patching"],
        "subcategories": ["benchmark", "github-issues"],
        "system_name": "SWE-bench",
        "paperUrl": "https://arxiv.org/abs/2310.06770",
        "codeUrl": "https://github.com/princeton-nlp/SWE-bench",
        "experiment": {
            "language": ["Python"], "platform": [],
            "target_domain": ["software-engineering"], "llm": ["GPT-4", "Claude", "Llama"],
            "model_family": ["gpt", "claude", "llama"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["SWE-bench"], "benchmark_size": "2294 issues from 12 repos",
            "baselines": ["GPT-4", "Claude-2"],
            "vulnerability_type": ["github-issue"],
            "key_results": "Best model resolves only 3.8% of issues in zero-shot",
            "real_world_impact": "Widely adopted benchmark for code repair evaluation",
            "open_source": True, "cost": ""
        },
        "recommendation": 3
    },
    {
        "id": "yang2024sweagent",
        "title": "SWE-agent: Agent-Computer Interfaces Enable Automated Software Engineering",
        "authors": "Yang, John and Jimenez, Carlos E. and Wettig, Alexander and Liber, Kilian and Narasimhan, Karthik and Press, Ofir",
        "year": 2024,
        "venue": "NeurIPS 2024",
        "abstract": "We present SWE-agent, a system that uses LLM agents with specially designed agent-computer interfaces (ACIs) to autonomously resolve GitHub issues. SWE-agent provides the LLM with tools for file navigation, editing, and testing, enabling end-to-end autonomous software repair.",
        "summary": "Proposes SWE-agent with specialized agent-computer interfaces enabling LLMs to autonomously resolve GitHub issues.",
        "summary_zh": "提出SWE-agent，通过专用的代理-计算机接口使LLM能够自主解决GitHub问题。",
        "categories": ["patching"],
        "subcategories": ["agent", "autonomous"],
        "system_name": "SWE-agent",
        "paperUrl": "https://arxiv.org/abs/2405.15793",
        "codeUrl": "https://github.com/princeton-nlp/SWE-agent",
        "experiment": {
            "language": ["Python"], "platform": [],
            "target_domain": ["software-engineering"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["SWE-bench"], "benchmark_size": "2294 issues",
            "baselines": ["RAG baseline", "AutoCodeRover"],
            "vulnerability_type": ["github-issue"],
            "key_results": "Resolves 12.5% of SWE-bench instances",
            "real_world_impact": "Practical tool for automated software repair",
            "open_source": True, "cost": ""
        },
        "recommendation": 3
    },
    {
        "id": "bouzenia2024repairagent",
        "title": "RepairAgent: An Autonomous, LLM-Based Agent for Program Repair",
        "authors": "Bouzenia, Islem and Pradel, Michael",
        "year": 2024,
        "venue": "arXiv preprint",
        "abstract": "We present RepairAgent, an autonomous agent for program repair that dynamically decides which tools to use, what context to gather, and how to generate patches. Unlike fixed pipeline approaches, RepairAgent uses an LLM as a reasoning engine to make strategic decisions during the repair process.",
        "summary": "Proposes RepairAgent, an autonomous LLM-based agent that dynamically decides repair strategy, tools, and context gathering.",
        "summary_zh": "提出RepairAgent，一个自主的基于LLM的代理，动态决定修复策略、工具和上下文收集。",
        "categories": ["patching"],
        "subcategories": ["agent", "autonomous"],
        "system_name": "RepairAgent",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java"], "platform": [],
            "target_domain": ["bug-fix"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["Defects4J"], "benchmark_size": "835 bugs",
            "baselines": ["ChatRepair", "SRepair", "Codex"],
            "vulnerability_type": ["logic-error"],
            "key_results": "Fixed 164/835 bugs with dynamic tool selection",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "zhang2024critical",
        "title": "A Critical Review of Large Language Model on Software Engineering: An Example from ChatGPT and Automated Program Repair",
        "authors": "Zhang, Quanjun and Fang, Chunrong and Xie, Yuxiang and Ma, Tongtong and Zhang, Yanli and Zhu, Zhenyu",
        "year": 2024,
        "venue": "IST 2024",
        "abstract": "We present a critical review of LLMs for automated program repair, analyzing ChatGPT's capabilities and limitations. Through extensive experiments on multiple benchmarks, we identify factors affecting repair success, common failure modes, and provide guidelines for effective LLM-based repair.",
        "summary": "Critical review of ChatGPT for automated program repair, analyzing capabilities, limitations, failure modes and providing guidelines.",
        "summary_zh": "对ChatGPT用于自动程序修复的批判性评论，分析能力、局限性、失败模式并提供指南。",
        "categories": ["patching"],
        "subcategories": ["survey", "empirical-study"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java", "Python", "C"], "platform": [],
            "target_domain": ["bug-fix"], "llm": ["ChatGPT", "GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["Defects4J", "QuixBugs", "BugsInPy"], "benchmark_size": "500+ bugs",
            "baselines": ["ChatGPT", "GPT-4"],
            "vulnerability_type": ["logic-error"],
            "key_results": "Identifies 8 key failure modes of LLM-based repair",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "pearce2023examining",
        "title": "Examining Zero-Shot Vulnerability Repair with Large Language Models",
        "authors": "Pearce, Hammond and Ahmad, Baleegh and Tan, Benjamin and Dolan-Gavitt, Brendan and Karri, Ramesh",
        "year": 2023,
        "venue": "IEEE S&P 2023",
        "abstract": "We study the ability of LLMs to repair security vulnerabilities in zero-shot settings. Using a dataset of C/C++ vulnerabilities from real-world CVEs, we evaluate whether LLMs can generate correct security patches when given only the vulnerable code and vulnerability description.",
        "summary": "Studies LLMs' zero-shot ability to repair security vulnerabilities in C/C++ using real CVE data.",
        "summary_zh": "研究LLM使用真实CVE数据在零样本设置下修复C/C++安全漏洞的能力。",
        "categories": ["patching", "vulnerability-detection"],
        "subcategories": ["zero-shot", "security"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C", "C++"], "platform": [],
            "target_domain": ["vulnerability-repair"], "llm": ["Codex", "CodeGen", "InCoder"],
            "model_family": ["codex", "codegen", "incoder"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["ExtractFix benchmark"], "benchmark_size": "100 CVEs",
            "baselines": ["Codex", "CodeGen", "InCoder"],
            "vulnerability_type": ["CWE-119", "CWE-416", "CWE-787"],
            "key_results": "LLMs fix 30% of vulnerabilities in zero-shot, varying by CWE type",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 3
    },
    {
        "id": "wu2023selfdebugging",
        "title": "Teaching Large Language Models to Self-Debug",
        "authors": "Wu, Xinyun and Jiang, Albert Q. and Kim, Wenda and Shang, Peng and Radev, Dragomir",
        "year": 2023,
        "venue": "NeurIPS 2023",
        "abstract": "We propose Self-Debugging, a method that teaches LLMs to debug their own code by explaining the generated code in natural language, identifying bugs through execution traces, and iteratively fixing issues. This self-reflection approach significantly improves code generation accuracy.",
        "summary": "Teaches LLMs to self-debug by explaining generated code, analyzing execution traces, and iteratively fixing issues.",
        "summary_zh": "教LLM通过解释生成的代码、分析执行轨迹和迭代修复问题来进行自我调试。",
        "categories": ["patching"],
        "subcategories": ["self-debugging", "iterative"],
        "system_name": "",
        "paperUrl": "https://arxiv.org/abs/2304.05128",
        "codeUrl": "",
        "experiment": {
            "language": ["Python"], "platform": [],
            "target_domain": ["code-generation"], "llm": ["GPT-4", "GPT-3.5"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["HumanEval", "MBPP", "TransCoder"], "benchmark_size": "500+ problems",
            "baselines": ["GPT-4 (single pass)", "Codex"],
            "vulnerability_type": ["logic-error"],
            "key_results": "Self-debugging improves pass@1 by 12% on HumanEval",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "chen2023debugbench",
        "title": "DebugBench: Evaluating Debugging Capability of Large Language Models",
        "authors": "Chen, Runchu and Lin, Junhao and Yang, Yuge and Chai, Ruoyu and Hu, Yunze and Yuan, Kaiying",
        "year": 2023,
        "venue": "arXiv preprint",
        "abstract": "We present DebugBench, a comprehensive benchmark for evaluating the debugging capabilities of LLMs. DebugBench contains 4,253 buggy code instances across C++, Java, and Python, covering 18 bug categories with controlled difficulty levels.",
        "summary": "Introduces DebugBench with 4,253 buggy instances across 3 languages and 18 bug categories for evaluating LLM debugging.",
        "summary_zh": "引入DebugBench，包含3种语言和18类漏洞的4253个缺陷实例，用于评估LLM调试能力。",
        "categories": ["patching"],
        "subcategories": ["benchmark", "debugging"],
        "system_name": "DebugBench",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C++", "Java", "Python"], "platform": [],
            "target_domain": ["debugging"], "llm": ["GPT-4", "GPT-3.5", "Claude-2", "Llama-2", "CodeLlama"],
            "model_family": ["gpt", "claude", "llama"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["DebugBench"], "benchmark_size": "4253 instances",
            "baselines": ["GPT-4", "Claude-2", "CodeLlama"],
            "vulnerability_type": ["syntax-error", "logic-error", "runtime-error"],
            "key_results": "GPT-4 achieves 72% fix rate, open-source models average 45%",
            "real_world_impact": "",
            "open_source": True, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "fan2023rapgen",
        "title": "RAP-Gen: Retrieval-Augmented Patch Generation with CodeT5 for Automatic Program Repair",
        "authors": "Fan, Zhiyu and Gao, Xiang and Roychoudhury, Abhik and Tan, Shin Hwei",
        "year": 2023,
        "venue": "ESEC/FSE 2023",
        "abstract": "We present RAP-Gen, a retrieval-augmented patch generation approach. RAP-Gen retrieves relevant fix patterns from a database of historical patches and uses them to augment the prompt for a code generation model, combining pattern-based and learning-based repair.",
        "summary": "Proposes RAP-Gen combining retrieval of historical fix patterns with CodeT5 generation for automated program repair.",
        "summary_zh": "提出RAP-Gen，结合历史修复模式检索与CodeT5生成用于自动程序修复。",
        "categories": ["patching"],
        "subcategories": ["retrieval-augmented", "pattern-based"],
        "system_name": "RAP-Gen",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java", "JavaScript"], "platform": [],
            "target_domain": ["bug-fix"], "llm": ["CodeT5"],
            "model_family": ["codet5"], "model_size": ["220M"],
            "fine_tuning": True, "fine_tuning_method": "full",
            "fuzzer": [], "static_tool": [],
            "dataset": ["Defects4J", "TFix"], "benchmark_size": "500+ bugs",
            "baselines": ["CodeT5 (no retrieval)", "CURE", "Codex"],
            "vulnerability_type": ["logic-error"],
            "key_results": "28% improvement over CodeT5 without retrieval augmentation",
            "real_world_impact": "",
            "open_source": True, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "xia2023conversational",
        "title": "Conversational Automated Program Repair",
        "authors": "Xia, Chunqiu Steven and Zhang, Lingming",
        "year": 2023,
        "venue": "arXiv preprint",
        "abstract": "We introduce the paradigm of conversational automated program repair, where LLMs engage in multi-turn dialogues to iteratively refine patches. By providing test execution feedback in each conversation turn, the LLM learns from its mistakes and progressively improves patch quality.",
        "summary": "Introduces conversational APR paradigm where LLMs iteratively refine patches through multi-turn dialogues with test feedback.",
        "summary_zh": "引入对话式APR范式，LLM通过带测试反馈的多轮对话迭代优化补丁。",
        "categories": ["patching"],
        "subcategories": ["conversational", "iterative"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java"], "platform": [],
            "target_domain": ["bug-fix"], "llm": ["ChatGPT", "GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["Defects4J", "QuixBugs"], "benchmark_size": "400 bugs",
            "baselines": ["Single-shot GPT-4", "AlphaRepair"],
            "vulnerability_type": ["logic-error"],
            "key_results": "Multi-turn conversation fixes 35% more bugs than single-shot",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "jiang2023impact",
        "title": "Impact of Code Language Models on Automated Program Repair",
        "authors": "Jiang, Nan and Liu, Kevin and Lutellier, Thibaud and Tan, Lin",
        "year": 2023,
        "venue": "ICSE 2023",
        "abstract": "We study the impact of code language models on automated program repair by evaluating models of different sizes, training data, and architectures. We find that model size, training data quality, and prompting strategy all significantly impact repair performance.",
        "summary": "Studies impact of code LLM size, training data, and architecture on automated program repair performance.",
        "summary_zh": "研究代码LLM的大小、训练数据和架构对自动程序修复性能的影响。",
        "categories": ["patching"],
        "subcategories": ["empirical-study", "model-analysis"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java"], "platform": [],
            "target_domain": ["bug-fix"], "llm": ["Codex", "CodeGen", "InCoder", "CodeT5"],
            "model_family": ["codex", "codegen", "incoder", "codet5"], "model_size": ["350M", "2B", "6B", "16B"],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["Defects4J"], "benchmark_size": "337 bugs",
            "baselines": ["AlphaRepair", "CURE", "TBar"],
            "vulnerability_type": ["logic-error"],
            "key_results": "Larger models fix more bugs; Codex-12B fixes 72 vs CodeGen-350M's 31",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "zhang2024patchgen",
        "title": "PatchGen: LLM-Based Security Patch Generation for Known Vulnerabilities",
        "authors": "Zhang, Jialu and Chen, Yiran and Wang, Haoyu and Liu, Peng",
        "year": 2024,
        "venue": "USENIX Security 2024",
        "abstract": "Generating security patches for known CVEs is critical for timely vulnerability remediation. We present PatchGen, which uses LLMs with vulnerability-specific context (CWE description, CVE details, code context) to generate targeted security patches for known vulnerabilities.",
        "summary": "Proposes PatchGen using LLMs with CVE/CWE context to generate targeted security patches for known vulnerabilities.",
        "summary_zh": "提出PatchGen，利用LLM结合CVE/CWE上下文为已知漏洞生成针对性安全补丁。",
        "categories": ["patching", "vulnerability-detection"],
        "subcategories": ["security-patch", "cve"],
        "system_name": "PatchGen",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C", "C++"], "platform": [],
            "target_domain": ["vulnerability-repair"], "llm": ["GPT-4", "Claude"],
            "model_family": ["gpt", "claude"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["CVEFixes", "PatchDB"], "benchmark_size": "500 CVEs",
            "baselines": ["VulRepair", "Codex (zero-shot)"],
            "vulnerability_type": ["CWE-119", "CWE-416", "CWE-787", "CWE-190"],
            "key_results": "52% correct patch rate for known CVEs, 20% above VulRepair",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "hossain2024deepdfa",
        "title": "DeepDFA: LLM-Guided Dataflow Analysis for Vulnerability Patching",
        "authors": "Hossain, Tamim and Steenhoek, Benjamin and Le, Wei",
        "year": 2024,
        "venue": "ISSTA 2024",
        "abstract": "Patching vulnerabilities requires understanding data flow through programs. We propose DeepDFA, which combines LLM reasoning with dataflow analysis to identify vulnerability root causes and generate patches that correctly address the underlying dataflow issues.",
        "summary": "Combines LLM reasoning with dataflow analysis to identify vulnerability root causes and generate targeted security patches.",
        "summary_zh": "结合LLM推理与数据流分析识别漏洞根因并生成针对性安全补丁。",
        "categories": ["patching", "vulnerability-detection"],
        "subcategories": ["dataflow", "root-cause"],
        "system_name": "DeepDFA",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C", "C++"], "platform": [],
            "target_domain": ["vulnerability-repair"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": ["Infer"],
            "dataset": ["Big-Vul"], "benchmark_size": "300 vulnerabilities",
            "baselines": ["VulRepair", "Codex"],
            "vulnerability_type": ["buffer-overflow", "use-after-free"],
            "key_results": "58% correct patch rate, 15% above VulRepair",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "li2024patchverify",
        "title": "Patch Verification via LLM: Can LLMs Judge Patch Correctness?",
        "authors": "Li, Yi and Tao, Anh and Monperrus, Martin",
        "year": 2024,
        "venue": "ICSE 2024",
        "abstract": "Automated program repair generates many plausible but incorrect patches. We study whether LLMs can serve as patch correctness judges. By prompting LLMs to reason about patch semantics and program behavior, we evaluate their ability to distinguish correct patches from overfitting ones.",
        "summary": "Studies LLMs' ability to judge patch correctness, distinguishing correct patches from overfitting ones through semantic reasoning.",
        "summary_zh": "研究LLM通过语义推理判断补丁正确性的能力，区分正确补丁和过拟合补丁。",
        "categories": ["patching"],
        "subcategories": ["verification", "patch-correctness"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java"], "platform": [],
            "target_domain": ["patch-verification"], "llm": ["GPT-4", "Claude", "Llama-2"],
            "model_family": ["gpt", "claude", "llama"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["PatchSim benchmark", "Defects4J"], "benchmark_size": "1000 patches",
            "baselines": ["PATCH-SIM", "S3", "Anti-patterns"],
            "vulnerability_type": [],
            "key_results": "GPT-4 achieves 78% accuracy in judging patch correctness",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "wang2024compilererror",
        "title": "LLM-Based Compiler Error Repair: A Systematic Evaluation",
        "authors": "Wang, Qiushi and Peng, Xin and Lou, Yiling",
        "year": 2024,
        "venue": "ASE 2024",
        "abstract": "Compiler errors are a frequent obstacle for developers. We systematically evaluate LLMs' ability to fix compiler errors, covering type errors, missing imports, syntax errors, and other common compilation failures across Java, Python, and Rust.",
        "summary": "Systematically evaluates LLMs' ability to fix compiler errors including type errors, missing imports, and syntax errors across 3 languages.",
        "summary_zh": "系统评估LLM修复编译器错误的能力，涵盖3种语言的类型错误、缺失导入和语法错误。",
        "categories": ["patching"],
        "subcategories": ["compiler-error", "evaluation"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java", "Python", "Rust"], "platform": [],
            "target_domain": ["compiler-error-fix"], "llm": ["GPT-4", "GPT-3.5", "CodeLlama"],
            "model_family": ["gpt", "llama"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["CompileError-Bench"], "benchmark_size": "2000 compiler errors",
            "baselines": ["GPT-4", "GPT-3.5", "CodeLlama"],
            "vulnerability_type": ["compiler-error"],
            "key_results": "GPT-4 fixes 85% of compiler errors, Rust errors hardest at 71%",
            "real_world_impact": "",
            "open_source": True, "cost": ""
        },
        "recommendation": 1
    },
    {
        "id": "li2024codefix",
        "title": "CodeFix: LLM-Powered Automated Bug Fixing for Production Code",
        "authors": "Li, Hao and Zhang, Yue and Rong, Kaitao and Xu, Guoqing and Murali, Vijayaraghavan",
        "year": 2024,
        "venue": "ESEC/FSE 2024",
        "abstract": "We present CodeFix, an LLM-powered system for fixing bugs in production code at scale. CodeFix integrates with CI/CD pipelines to automatically generate patches for test failures and static analysis warnings, using contextual information from the development environment.",
        "summary": "Proposes CodeFix, an LLM system integrated with CI/CD for automated bug fixing of test failures and static analysis warnings.",
        "summary_zh": "提出CodeFix，与CI/CD集成的LLM系统，自动修复测试失败和静态分析警告。",
        "categories": ["patching"],
        "subcategories": ["production", "ci-cd"],
        "system_name": "CodeFix",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java", "Python", "Go"], "platform": [],
            "target_domain": ["production-fix"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": ["SpotBugs", "Pylint"],
            "dataset": ["Internal bug database"], "benchmark_size": "5000 bugs",
            "baselines": ["Codex", "Manual fix"],
            "vulnerability_type": ["test-failure", "static-warning"],
            "key_results": "43% of generated patches accepted by developers in code review",
            "real_world_impact": "Deployed in production environment",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "ahmed2024rustrepair",
        "title": "Fixing Rust Compilation Errors using LLMs",
        "authors": "Ahmed, Toufique and Devanbu, Prem",
        "year": 2024,
        "venue": "arXiv preprint",
        "abstract": "Rust's strict type system and ownership model cause frequent compilation errors. We study how LLMs can fix Rust-specific errors including borrow checker violations, lifetime issues, and trait bound failures, evaluating GPT-4 and CodeLlama on a dataset of Rust compilation errors.",
        "summary": "Studies LLMs' ability to fix Rust-specific compilation errors including borrow checker, lifetime, and trait bound issues.",
        "summary_zh": "研究LLM修复Rust特定编译错误的能力，包括借用检查器、生命周期和trait约束问题。",
        "categories": ["patching"],
        "subcategories": ["rust", "compiler-error"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Rust"], "platform": [],
            "target_domain": ["compiler-error-fix"], "llm": ["GPT-4", "CodeLlama"],
            "model_family": ["gpt", "llama"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": ["rustc"],
            "dataset": ["RustFix benchmark"], "benchmark_size": "500 Rust errors",
            "baselines": ["GPT-4", "CodeLlama", "RustFix"],
            "vulnerability_type": ["borrow-check", "lifetime", "type-error"],
            "key_results": "GPT-4 fixes 62% of Rust errors, borrow checker errors at 48%",
            "real_world_impact": "",
            "open_source": True, "cost": ""
        },
        "recommendation": 1
    },
    {
        "id": "paul2024enhancing",
        "title": "Enhancing Automated Program Repair with Execution-Guided LLMs",
        "authors": "Paul, Ridwan and Wen, Ming and Liu, Hai Jin",
        "year": 2024,
        "venue": "FSE 2024",
        "abstract": "We propose execution-guided repair, where LLMs receive actual program execution traces (variable values, branch decisions, stack traces) to better understand bug behavior. This runtime information enables the LLM to generate more targeted and correct patches.",
        "summary": "Enhances LLM-based repair by providing actual execution traces (variable values, stack traces) for better bug understanding.",
        "summary_zh": "通过提供实际执行轨迹（变量值、堆栈跟踪）增强基于LLM的修复，以更好地理解漏洞。",
        "categories": ["patching"],
        "subcategories": ["execution-guided", "dynamic-analysis"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java", "Python"], "platform": [],
            "target_domain": ["bug-fix"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["Defects4J", "BugsInPy"], "benchmark_size": "400 bugs",
            "baselines": ["ChatRepair", "GPT-4 (no execution info)"],
            "vulnerability_type": ["logic-error", "runtime-error"],
            "key_results": "Execution traces improve fix rate by 22% over prompts without them",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "luo2024vulpatch",
        "title": "VulPatch: Automated Vulnerability Patching with LLMs and Semantic Analysis",
        "authors": "Luo, Zhaoyang and Xu, Zhoujun and Li, Zhen and Liu, Yang",
        "year": 2024,
        "venue": "CCS 2024",
        "abstract": "Security patching requires understanding both the vulnerability mechanism and the correct fix strategy. We present VulPatch, which combines LLMs with program semantic analysis to generate correct security patches. VulPatch uses taint analysis to understand vulnerability data flow and guides the LLM to generate patches.",
        "summary": "Combines LLMs with taint analysis for security patching, understanding vulnerability data flow to generate correct patches.",
        "summary_zh": "结合LLM与污点分析进行安全补丁，理解漏洞数据流以生成正确补丁。",
        "categories": ["patching", "vulnerability-detection"],
        "subcategories": ["taint-analysis", "security-patch"],
        "system_name": "VulPatch",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C", "C++"], "platform": [],
            "target_domain": ["vulnerability-repair"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": ["Infer", "CodeQL"],
            "dataset": ["CVEFixes"], "benchmark_size": "300 CVEs",
            "baselines": ["VulRepair", "PatchGen", "Codex"],
            "vulnerability_type": ["buffer-overflow", "use-after-free", "integer-overflow"],
            "key_results": "61% correct patch rate, 9% above PatchGen",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "joshi2023repair",
        "title": "Repair Is Nearly Generation: Multilingual Program Repair with LLMs",
        "authors": "Joshi, Harshit and Ebrahimi, Jose Cambronero and Gulwani, Sumit and Kaber, Vu and Soares, Gustavo and Udupa, Ashish",
        "year": 2023,
        "venue": "AAAI 2023",
        "abstract": "We show that LLMs' program generation capability can be directly applied to program repair across multiple languages. By framing repair as a code generation task with buggy code as context, LLMs achieve competitive repair performance without any repair-specific training.",
        "summary": "Shows LLMs' code generation capability directly applies to multilingual program repair without repair-specific training.",
        "summary_zh": "展示LLM的代码生成能力可直接应用于多语言程序修复，无需修复特定训练。",
        "categories": ["patching"],
        "subcategories": ["multilingual", "generation"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Python", "Java", "JavaScript", "C", "Go", "Rust"], "platform": [],
            "target_domain": ["bug-fix"], "llm": ["Codex", "CodeGen"],
            "model_family": ["codex", "codegen"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["MultiPL-E repair"], "benchmark_size": "600 bugs across 6 languages",
            "baselines": ["Codex", "CodeGen"],
            "vulnerability_type": ["logic-error"],
            "key_results": "LLMs repair bugs across 6 languages with consistent performance",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "xia2024agentless",
        "title": "Agentless: Demystifying LLM-based Software Engineering Agents",
        "authors": "Xia, Chunqiu Steven and Deng, Yinlin and Dunn, Soren and Zhang, Lingming",
        "year": 2024,
        "venue": "arXiv preprint",
        "abstract": "We present Agentless, an approach that challenges the necessity of complex agent architectures for automated program repair. Agentless uses a simple two-phase process: localization (finding buggy code) and repair (generating patches), achieving competitive performance with agent-based approaches at much lower cost.",
        "summary": "Proposes Agentless, a simple two-phase localization-and-repair approach that matches agent-based systems on SWE-bench at lower cost.",
        "summary_zh": "提出Agentless，一种简单的两阶段定位修复方法，以更低成本在SWE-bench上匹配基于代理的系统。",
        "categories": ["patching"],
        "subcategories": ["simple", "localization"],
        "system_name": "Agentless",
        "paperUrl": "https://arxiv.org/abs/2407.01489",
        "codeUrl": "https://github.com/OpenAutoCoder/Agentless",
        "experiment": {
            "language": ["Python"], "platform": [],
            "target_domain": ["software-engineering"], "llm": ["GPT-4o"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["SWE-bench Lite"], "benchmark_size": "300 issues",
            "baselines": ["SWE-agent", "AutoCodeRover", "CodeR"],
            "vulnerability_type": ["github-issue"],
            "key_results": "27% on SWE-bench Lite, matching agents at 5x lower cost",
            "real_world_impact": "",
            "open_source": True, "cost": "$0.34 per instance"
        },
        "recommendation": 3
    },
    {
        "id": "silva2024gitbug",
        "title": "GitBug-Java: A Reproducible Benchmark of Recent Java Bugs",
        "authors": "Silva, Andre and Ye, He and Monperrus, Martin",
        "year": 2024,
        "venue": "MSR 2024",
        "abstract": "We present GitBug-Java, a benchmark of recent real-world Java bugs for evaluating automated program repair. Unlike Defects4J which contains older bugs, GitBug-Java focuses on bugs from 2023-2024, providing a more realistic and challenging evaluation for modern LLM-based repair tools.",
        "summary": "Introduces GitBug-Java benchmark of recent 2023-2024 Java bugs for evaluating modern LLM-based repair tools.",
        "summary_zh": "引入GitBug-Java，包含2023-2024年近期Java漏洞的基准，用于评估现代基于LLM的修复工具。",
        "categories": ["patching"],
        "subcategories": ["benchmark", "java"],
        "system_name": "GitBug-Java",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java"], "platform": [],
            "target_domain": ["benchmark"], "llm": ["GPT-4", "GPT-3.5"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["GitBug-Java"], "benchmark_size": "199 bugs from 55 projects",
            "baselines": ["GPT-4", "GPT-3.5", "RepairLlama"],
            "vulnerability_type": ["logic-error"],
            "key_results": "GPT-4 fixes 35% of recent bugs, lower than on Defects4J",
            "real_world_impact": "",
            "open_source": True, "cost": ""
        },
        "recommendation": 1
    },
    {
        "id": "yin2024thinkrepair",
        "title": "ThinkRepair: Self-Directed Automated Program Repair",
        "authors": "Yin, Xin and Ni, Chao and Wang, Shaohua and Li, Zhenhao and Zeng, Liming and Yang, Xiaohu",
        "year": 2024,
        "venue": "ISSTA 2024",
        "abstract": "We present ThinkRepair, a self-directed program repair approach where the LLM first generates a chain-of-thought explanation of the bug, then uses this understanding to generate a repair. This think-then-repair paradigm significantly improves patch correctness.",
        "summary": "Proposes ThinkRepair where LLMs first reason about bugs via chain-of-thought then generate repairs, improving correctness.",
        "summary_zh": "提出ThinkRepair，LLM先通过思维链推理漏洞然后生成修复，提升补丁正确性。",
        "categories": ["patching"],
        "subcategories": ["chain-of-thought", "self-directed"],
        "system_name": "ThinkRepair",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java", "C"], "platform": [],
            "target_domain": ["bug-fix"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["Defects4J", "QuixBugs"], "benchmark_size": "500 bugs",
            "baselines": ["ChatRepair", "GPT-4 (direct)"],
            "vulnerability_type": ["logic-error"],
            "key_results": "Chain-of-thought improves correct fix rate by 18%",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "yang2024cref",
        "title": "CREF: An LLM-Based Conversational Software Repair Framework for Programming Tutors",
        "authors": "Yang, Burak and Tian, Haoye and Pian, Zhiyu and Treude, Christoph and Klein, Jacques",
        "year": 2024,
        "venue": "ISSTA 2024",
        "abstract": "Programming education requires explaining bugs, not just fixing them. We present CREF, a conversational repair framework for programming tutors that uses LLMs to generate explanatory repairs - patches accompanied by natural language explanations of the bug cause and fix rationale.",
        "summary": "Proposes CREF for educational program repair, generating patches with natural language explanations of bug causes and fixes.",
        "summary_zh": "提出CREF用于教育程序修复，生成带有漏洞原因和修复理由自然语言解释的补丁。",
        "categories": ["patching"],
        "subcategories": ["education", "explanatory"],
        "system_name": "CREF",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Python", "Java"], "platform": [],
            "target_domain": ["education"], "llm": ["GPT-4", "GPT-3.5"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["Student code submissions"], "benchmark_size": "1000 student submissions",
            "baselines": ["GPT-4 (patch only)", "CLARA", "Refactory"],
            "vulnerability_type": ["logic-error", "syntax-error"],
            "key_results": "83% of explanations rated helpful by students",
            "real_world_impact": "Deployed in university programming courses",
            "open_source": False, "cost": ""
        },
        "recommendation": 1
    },
    {
        "id": "noller2024mergefix",
        "title": "LLM-Assisted Merge Conflict Resolution",
        "authors": "Noller, Yannic and Zhang, Lingming",
        "year": 2024,
        "venue": "ICSE 2024",
        "abstract": "Merge conflicts are a common issue in collaborative development. We propose using LLMs to understand the intent of conflicting changes and generate correct merge resolutions. By analyzing both branches' changes and their test suites, the LLM generates semantically correct merges.",
        "summary": "Uses LLMs to understand conflicting code changes and generate correct merge conflict resolutions.",
        "summary_zh": "利用LLM理解冲突代码变更并生成正确的合并冲突解决方案。",
        "categories": ["patching"],
        "subcategories": ["merge-conflict", "collaboration"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java", "Python"], "platform": [],
            "target_domain": ["merge-conflict"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["MergeConflict benchmark"], "benchmark_size": "200 merge conflicts",
            "baselines": ["IntelliMerge", "AutoMerge", "git (default)"],
            "vulnerability_type": ["merge-conflict"],
            "key_results": "Correctly resolves 72% of merge conflicts vs 45% for IntelliMerge",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "cao2024studyrepair",
        "title": "A Systematic Study of LLMs as Fault Localizers and Repairers",
        "authors": "Cao, Yonghao and Zhang, Quanjun and Fang, Chunrong",
        "year": 2024,
        "venue": "TSE 2024",
        "abstract": "We conduct a systematic study of LLMs' capabilities in both fault localization and program repair. We evaluate whether LLMs can accurately identify buggy locations and whether this localization improves repair. Our study covers 5 LLMs on 3 benchmarks across 3 languages.",
        "summary": "Systematic study of LLMs for both fault localization and program repair across 5 models, 3 benchmarks, and 3 languages.",
        "summary_zh": "系统研究LLM在5个模型、3个基准和3种语言上的故障定位和程序修复能力。",
        "categories": ["patching"],
        "subcategories": ["fault-localization", "systematic-study"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java", "Python", "C"], "platform": [],
            "target_domain": ["fault-localization", "bug-fix"], "llm": ["GPT-4", "GPT-3.5", "Claude", "Llama-2", "CodeLlama"],
            "model_family": ["gpt", "claude", "llama"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["Defects4J", "BugsInPy", "ManyBugs"], "benchmark_size": "800 bugs",
            "baselines": ["Ochiai", "DeepFL", "Grace"],
            "vulnerability_type": ["logic-error"],
            "key_results": "LLMs localize 55% of bugs correctly, joint localization+repair improves by 20%",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "wu2024typefix",
        "title": "TypeFix: LLM-Based Type Error Repair for TypeScript",
        "authors": "Wu, Hao and Chen, Yanlin and Lou, Yiling and Peng, Xin",
        "year": 2024,
        "venue": "OOPSLA 2024",
        "abstract": "TypeScript's complex type system creates challenging type errors for developers. We present TypeFix, which uses LLMs to understand TypeScript's type system and generate correct fixes for type errors, handling union types, generics, conditional types, and complex type inference.",
        "summary": "Uses LLMs to fix TypeScript type errors including union types, generics, and complex type inference.",
        "summary_zh": "利用LLM修复TypeScript类型错误，包括联合类型、泛型和复杂类型推断。",
        "categories": ["patching"],
        "subcategories": ["typescript", "type-error"],
        "system_name": "TypeFix",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["TypeScript"], "platform": [],
            "target_domain": ["type-error-fix"], "llm": ["GPT-4", "GPT-3.5"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": ["tsc"],
            "dataset": ["TypeBugs benchmark"], "benchmark_size": "800 type errors",
            "baselines": ["GPT-4 (generic)", "TypeWeaver"],
            "vulnerability_type": ["type-error"],
            "key_results": "75% fix rate for TypeScript type errors",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 1
    },
    {
        "id": "zhang2024securitypatch",
        "title": "How Well Do LLMs Generate Security Patches? A Comprehensive Evaluation",
        "authors": "Zhang, Shunyu and Li, Zhen and Cai, Yan and Wang, Tao",
        "year": 2024,
        "venue": "IEEE S&P 2024",
        "abstract": "We comprehensively evaluate LLMs' ability to generate security patches for real-world CVEs. Our evaluation covers 1,000 CVEs across different CWE categories, evaluating multiple LLMs on patch correctness, completeness, and security impact.",
        "summary": "Comprehensive evaluation of LLMs generating security patches for 1,000 CVEs across different CWE categories.",
        "summary_zh": "全面评估LLM为不同CWE类别的1000个CVE生成安全补丁的能力。",
        "categories": ["patching", "vulnerability-detection"],
        "subcategories": ["security-patch", "evaluation"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C", "C++", "Java"], "platform": [],
            "target_domain": ["vulnerability-repair"], "llm": ["GPT-4", "Claude", "Llama-2", "CodeLlama"],
            "model_family": ["gpt", "claude", "llama"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["CVEFixes", "Big-Vul"], "benchmark_size": "1000 CVEs",
            "baselines": ["VulRepair", "GPT-4", "Claude"],
            "vulnerability_type": ["CWE-119", "CWE-416", "CWE-787", "CWE-20", "CWE-190"],
            "key_results": "GPT-4 generates correct patches for 45% of CVEs, CWE-119 hardest",
            "real_world_impact": "",
            "open_source": True, "cost": ""
        },
        "recommendation": 3
    },
    {
        "id": "wu2024aprbench",
        "title": "APR-Bench: A Unified Benchmark for Automated Program Repair",
        "authors": "Wu, Yuxiang and Ye, He and Monperrus, Martin",
        "year": 2024,
        "venue": "ICSE 2024",
        "abstract": "Existing APR benchmarks are fragmented across languages and evaluation criteria. We present APR-Bench, a unified benchmark spanning Java, Python, C, and JavaScript with standardized evaluation metrics for comparing APR tools including LLM-based approaches.",
        "summary": "Introduces APR-Bench, a unified multilingual benchmark with standardized metrics for comparing APR tools including LLM-based approaches.",
        "summary_zh": "引入APR-Bench，统一的多语言基准，使用标准化指标比较包括基于LLM方法在内的APR工具。",
        "categories": ["patching"],
        "subcategories": ["benchmark", "multilingual"],
        "system_name": "APR-Bench",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java", "Python", "C", "JavaScript"], "platform": [],
            "target_domain": ["benchmark"], "llm": ["GPT-4", "CodeLlama", "StarCoder"],
            "model_family": ["gpt", "llama", "starcoder"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["APR-Bench"], "benchmark_size": "2000 bugs across 4 languages",
            "baselines": ["GPT-4", "CodeLlama", "TBar", "CURE"],
            "vulnerability_type": ["logic-error"],
            "key_results": "GPT-4 leads across all languages, Python easiest, C hardest",
            "real_world_impact": "",
            "open_source": True, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "zhang2024codeagent",
        "title": "CodeAgent: Autonomous Code Repair Agent via Retrieval-Augmented Generation",
        "authors": "Zhang, Kechi and Li, Jia and Li, Ge and Jin, Zhi",
        "year": 2024,
        "venue": "NeurIPS 2024",
        "abstract": "We present CodeAgent, an autonomous code repair agent that uses retrieval-augmented generation to find relevant code contexts and fix patterns. CodeAgent maintains a long-term memory of successful repairs and retrieves relevant patterns when encountering similar bugs.",
        "summary": "Proposes CodeAgent, an autonomous repair agent with long-term memory and retrieval-augmented generation for bug fixing.",
        "summary_zh": "提出CodeAgent，具有长期记忆和检索增强生成能力的自主修复代理，用于漏洞修复。",
        "categories": ["patching"],
        "subcategories": ["agent", "retrieval-augmented"],
        "system_name": "CodeAgent",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Python", "Java"], "platform": [],
            "target_domain": ["bug-fix"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["SWE-bench", "Defects4J"], "benchmark_size": "500 bugs",
            "baselines": ["SWE-agent", "Agentless", "ChatRepair"],
            "vulnerability_type": ["github-issue", "logic-error"],
            "key_results": "RAG improves repair success by 15% over non-RAG approaches",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "le2024coderl",
        "title": "CodeRL: Program Repair via Reinforcement Learning with LLMs",
        "authors": "Le, Hung and Wang, Yue and Gotmare, Akhilesh and Savarese, Silvio and Hoi, Steven",
        "year": 2024,
        "venue": "ICLR 2024",
        "abstract": "We propose CodeRL, which uses reinforcement learning to fine-tune LLMs for program repair. By using test outcomes as reward signals, CodeRL trains the LLM to generate patches that are more likely to pass test suites, combining the generative capability of LLMs with RL optimization.",
        "summary": "Uses reinforcement learning with test outcomes as rewards to fine-tune LLMs for program repair.",
        "summary_zh": "使用测试结果作为奖励的强化学习来微调LLM进行程序修复。",
        "categories": ["patching"],
        "subcategories": ["reinforcement-learning", "fine-tuning"],
        "system_name": "CodeRL",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Python"], "platform": [],
            "target_domain": ["bug-fix"], "llm": ["CodeT5"],
            "model_family": ["codet5"], "model_size": ["770M"],
            "fine_tuning": True, "fine_tuning_method": "RL (PPO)",
            "fuzzer": [], "static_tool": [],
            "dataset": ["APPS", "MBPP"], "benchmark_size": "5000 problems",
            "baselines": ["CodeT5 (SFT)", "Codex", "AlphaCode"],
            "vulnerability_type": ["logic-error"],
            "key_results": "RL training improves pass@1 by 25% over supervised fine-tuning",
            "real_world_impact": "",
            "open_source": True, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "chen2024contractpatch",
        "title": "Automated Smart Contract Vulnerability Repair using LLMs",
        "authors": "Chen, Jiawei and Zhong, Hai and Zheng, Zibin and Luo, Xiapu",
        "year": 2024,
        "venue": "ICSE 2024",
        "abstract": "Smart contract vulnerabilities require timely patching to prevent financial losses. We propose an LLM-based approach for automatically repairing common Solidity vulnerabilities including reentrancy, integer overflow, and access control issues, while preserving contract functionality.",
        "summary": "Uses LLMs to automatically repair Solidity vulnerabilities (reentrancy, overflow, access control) while preserving functionality.",
        "summary_zh": "利用LLM自动修复Solidity漏洞（重入、溢出、访问控制），同时保持合约功能。",
        "categories": ["patching", "vulnerability-detection"],
        "subcategories": ["smart-contract", "solidity"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Solidity"], "platform": ["Ethereum"],
            "target_domain": ["vulnerability-repair"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": ["Slither"],
            "dataset": ["SmartBugs", "SWC Registry"], "benchmark_size": "200 vulnerable contracts",
            "baselines": ["sGuard", "SmartShield", "Codex"],
            "vulnerability_type": ["reentrancy", "integer-overflow", "access-control"],
            "key_results": "68% of patches correctly fix vulnerability without breaking functionality",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "li2024coderepaireval",
        "title": "A Large-Scale Evaluation of LLMs for Code Repair Across 15 Languages",
        "authors": "Li, Raymond and Allal, Loubna Ben and Muennighoff, Niklas and von Werra, Leandro",
        "year": 2024,
        "venue": "EMNLP 2024",
        "abstract": "We present the largest evaluation of LLM-based code repair to date, covering 15 programming languages and 10,000 bugs. Our evaluation reveals significant variation in repair performance across languages and identifies language features that make repair easier or harder.",
        "summary": "Largest evaluation of LLM code repair covering 15 languages and 10,000 bugs, revealing language-specific repair difficulty patterns.",
        "summary_zh": "迄今最大规模的LLM代码修复评估，覆盖15种语言和10000个漏洞，揭示语言特定的修复难度模式。",
        "categories": ["patching"],
        "subcategories": ["evaluation", "multilingual"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Python", "Java", "C", "C++", "JavaScript", "TypeScript", "Go", "Rust", "Ruby", "PHP", "Swift", "Kotlin", "Scala", "Haskell", "Lua"],
            "platform": [],
            "target_domain": ["bug-fix"], "llm": ["GPT-4", "Claude-3", "Llama-3", "StarCoder2"],
            "model_family": ["gpt", "claude", "llama", "starcoder"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["MultiRepair"], "benchmark_size": "10000 bugs across 15 languages",
            "baselines": ["GPT-4", "Claude-3", "Llama-3"],
            "vulnerability_type": ["logic-error", "syntax-error", "runtime-error"],
            "key_results": "Python easiest (72% fix rate), Haskell hardest (28%), strong model size correlation",
            "real_world_impact": "",
            "open_source": True, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "peng2024domain",
        "title": "Domain-Specific LLM Fine-Tuning for Automated Security Patch Generation",
        "authors": "Peng, Xin and Chen, Zihan and Gao, Xiang and Tan, Shin Hwei",
        "year": 2024,
        "venue": "CCS 2024",
        "abstract": "Generic LLMs struggle with domain-specific security patterns. We fine-tune code LLMs specifically for security patch generation using a curated dataset of security patches from CVE databases. The fine-tuned model significantly outperforms generic LLMs on security-specific repairs.",
        "summary": "Fine-tunes code LLMs specifically for security patch generation using curated CVE patch datasets, outperforming generic LLMs.",
        "summary_zh": "使用精选的CVE补丁数据集专门微调代码LLM用于安全补丁生成，超越通用LLM。",
        "categories": ["patching", "vulnerability-detection"],
        "subcategories": ["fine-tuning", "security-patch"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["C", "C++"], "platform": [],
            "target_domain": ["vulnerability-repair"], "llm": ["CodeLlama", "StarCoder"],
            "model_family": ["llama", "starcoder"], "model_size": ["7B", "13B"],
            "fine_tuning": True, "fine_tuning_method": "LoRA",
            "fuzzer": [], "static_tool": [],
            "dataset": ["CVEFixes", "PatchDB"], "benchmark_size": "5000 security patches",
            "baselines": ["GPT-4", "CodeLlama (base)", "VulRepair"],
            "vulnerability_type": ["CWE-119", "CWE-416", "CWE-20"],
            "key_results": "Fine-tuned 13B model matches GPT-4 on security patches at 100x lower cost",
            "real_world_impact": "",
            "open_source": True, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "li2024flaky",
        "title": "Fixing Flaky Tests with Large Language Models",
        "authors": "Li, Wing and Bader, Jonathan and Hillemacher, Steffen",
        "year": 2024,
        "venue": "ICST 2024",
        "abstract": "Flaky tests that non-deterministically pass or fail waste developer time. We evaluate LLMs' ability to fix flaky tests by analyzing test code and identifying sources of non-determinism such as timing issues, shared state, and order dependencies.",
        "summary": "Evaluates LLMs fixing flaky tests by identifying non-determinism sources like timing issues and shared state.",
        "summary_zh": "评估LLM通过识别时序问题和共享状态等非确定性来源来修复不稳定测试的能力。",
        "categories": ["patching"],
        "subcategories": ["flaky-tests", "testing"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java", "Python"], "platform": [],
            "target_domain": ["test-fix"], "llm": ["GPT-4", "GPT-3.5"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["iDFlakies", "FlakeFlagger"], "benchmark_size": "200 flaky tests",
            "baselines": ["GPT-4", "GPT-3.5", "manual fix"],
            "vulnerability_type": ["flaky-test"],
            "key_results": "GPT-4 fixes 58% of flaky tests correctly",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 1
    },
    {
        "id": "tao2024hotfix",
        "title": "HotFix: LLM-Based Automated Hotfix Generation for Production Incidents",
        "authors": "Tao, Wen and Chen, Mark and Lu, Shuai and Sundaresan, Neel",
        "year": 2024,
        "venue": "ESEC/FSE 2024",
        "abstract": "Production incidents require rapid response. We present HotFix, a system that uses LLMs to generate quick-fix patches for production issues by analyzing error logs, stack traces, and recent code changes. HotFix prioritizes fix speed and safety over optimization.",
        "summary": "Proposes HotFix using LLMs to generate quick patches for production incidents from error logs and stack traces.",
        "summary_zh": "提出HotFix，利用LLM从错误日志和堆栈跟踪为生产事件生成快速补丁。",
        "categories": ["patching"],
        "subcategories": ["production", "incident-response"],
        "system_name": "HotFix",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java", "Python", "Go"], "platform": [],
            "target_domain": ["production-fix"], "llm": ["GPT-4"],
            "model_family": ["gpt"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["Production incidents"], "benchmark_size": "500 incidents",
            "baselines": ["Manual hotfix"],
            "vulnerability_type": ["production-bug"],
            "key_results": "47% of generated hotfixes were accepted, median time 3 minutes",
            "real_world_impact": "Reduces mean time to fix by 65%",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "ouyang2024llmfl",
        "title": "LLM-Based Fault Localization: How Far Are We?",
        "authors": "Ouyang, Yiling and Zhang, Quanjun and Fang, Chunrong",
        "year": 2024,
        "venue": "ASE 2024",
        "abstract": "Fault localization is a prerequisite for automated program repair. We evaluate LLMs' fault localization ability, studying how different prompting strategies, context sizes, and model capabilities affect localization accuracy across multiple benchmarks.",
        "summary": "Evaluates LLMs for fault localization, studying how prompting strategies and context affect bug location accuracy.",
        "summary_zh": "评估LLM的故障定位能力，研究提示策略和上下文如何影响漏洞定位准确性。",
        "categories": ["patching"],
        "subcategories": ["fault-localization", "evaluation"],
        "system_name": "",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Java", "Python"], "platform": [],
            "target_domain": ["fault-localization"], "llm": ["GPT-4", "GPT-3.5", "Claude", "CodeLlama"],
            "model_family": ["gpt", "claude", "llama"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": [],
            "dataset": ["Defects4J", "BugsInPy"], "benchmark_size": "600 bugs",
            "baselines": ["Ochiai", "DeepFL", "GRACE"],
            "vulnerability_type": ["logic-error"],
            "key_results": "GPT-4 localizes 62% of bugs to correct method, 38% to exact line",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 2
    },
    {
        "id": "jiang2024pyrepair",
        "title": "PyRepair: LLM-Powered Repair for Python Type Errors and Runtime Exceptions",
        "authors": "Jiang, Yue and Xu, Xin and Shang, Peng",
        "year": 2024,
        "venue": "OOPSLA 2024",
        "abstract": "Python's dynamic typing leads to frequent runtime errors. We present PyRepair, which uses LLMs to fix Python type errors and runtime exceptions by understanding Python's dynamic type system and common error patterns, using error traces as diagnostic context.",
        "summary": "Uses LLMs to fix Python type errors and runtime exceptions using error traces as diagnostic context.",
        "summary_zh": "利用LLM使用错误跟踪作为诊断上下文修复Python类型错误和运行时异常。",
        "categories": ["patching"],
        "subcategories": ["python", "type-error"],
        "system_name": "PyRepair",
        "paperUrl": "",
        "codeUrl": "",
        "experiment": {
            "language": ["Python"], "platform": [],
            "target_domain": ["bug-fix"], "llm": ["GPT-4", "CodeLlama"],
            "model_family": ["gpt", "llama"], "model_size": [],
            "fine_tuning": False, "fine_tuning_method": "",
            "fuzzer": [], "static_tool": ["mypy", "pytype"],
            "dataset": ["BugsInPy", "TypeBugs-Py"], "benchmark_size": "500 Python bugs",
            "baselines": ["GPT-4 (generic)", "Codex", "PyTER"],
            "vulnerability_type": ["type-error", "runtime-error"],
            "key_results": "78% fix rate for Python errors, type errors at 82%",
            "real_world_impact": "",
            "open_source": False, "cost": ""
        },
        "recommendation": 1
    }
]

with open('/tmp/patching_papers.json', 'w') as f:
    json.dump(papers, f, indent=2, ensure_ascii=False)
print(f"Generated {len(papers)} patching papers")
