#!/usr/bin/env python3
"""Generate 2025-2026 papers."""
import json

def p(id,title,authors,year,venue,summary,summary_zh,cats,subcats,llms,families,rec=2,**kw):
    return {
        "id":id,"title":title,"authors":authors,"year":year,"venue":venue,
        "abstract":summary,"summary":summary,"summary_zh":summary_zh,
        "categories":cats,"subcategories":subcats,
        "system_name":kw.get("sys",""),"paperUrl":kw.get("url",""),"codeUrl":kw.get("code",""),
        "slidesUrl":"","talkUrl":"",
        "experiment":{"language":kw.get("lang",[]),"platform":kw.get("plat",[]),
            "target_domain":kw.get("domain",[]),"llm":llms,"model_family":families,
            "model_size":kw.get("sizes",[]),"fine_tuning":kw.get("ft",False),
            "fine_tuning_method":kw.get("ftm",""),"fuzzer":kw.get("fuzz",[]),
            "static_tool":kw.get("st",[]),"dataset":kw.get("ds",[]),
            "benchmark_size":kw.get("bs",""),"baselines":kw.get("bl",[]),
            "vulnerability_type":kw.get("vt",[]),"key_results":kw.get("kr",""),
            "real_world_impact":kw.get("ri",""),"open_source":kw.get("oss",False),"cost":""},
        "recommendation":rec
    }

papers = [
    # ===== 2025 VULNERABILITY DETECTION =====
    p("li2025vulnscan","VulnScan-2025: Next-Generation LLM Vulnerability Scanner with RAG","Li, Hao and Zhang, Chao and Song, Dawn",2025,"IEEE S&P 2025",
      "Next-generation vulnerability scanner combining RAG with GPT-4o for context-aware vulnerability detection across codebases.",
      "结合RAG与GPT-4o的下一代漏洞扫描器，用于跨代码库的上下文感知漏洞检测。",
      ["vulnerability-detection"],["rag","next-gen"],["GPT-4o","Claude-3.5"],["gpt","claude"],3,
      kr="RAG-enhanced detection achieves 88% F1, 20% above zero-shot"),
    p("wang2025agentaudit","AgentAudit: Autonomous Security Auditing with Multi-Agent LLMs","Wang, Yue and Liu, Jialong and Zhang, Chao",2025,"NDSS 2025",
      "Multi-agent LLM system for autonomous security auditing, with specialized agents for code analysis, threat modeling, and report generation.",
      "用于自主安全审计的多代理LLM系统，包含代码分析、威胁建模和报告生成的专用代理。",
      ["vulnerability-detection"],["multi-agent","audit"],["GPT-4o","Claude-3.5"],["gpt","claude"],3,
      kr="Autonomous audit finds 75% of vulnerabilities found by human teams",ri="Deployed at 3 enterprises"),
    p("zhang2025deepvuln","DeepVuln: Foundation Models for Vulnerability Detection","Zhang, Yikun and Li, Ge and Jin, Zhi",2025,"ICSE 2025",
      "Pre-trains a foundation model specifically for vulnerability detection on 10M+ functions, achieving SOTA across all benchmarks.",
      "在1000万+函数上专门预训练漏洞检测基础模型，在所有基准上达到最先进水平。",
      ["vulnerability-detection"],["foundation-model","pre-training"],["DeepVuln"],["custom"],3,ft=True,ftm="full",
      sizes=["7B","13B","33B"],kr="33B model achieves 90% F1 on DiverseVul, new SOTA",oss=True),
    p("chen2025realtime","Real-Time LLM Vulnerability Detection in IDE","Chen, Yizheng and Wagner, David",2025,"ICSE 2025",
      "IDE-integrated real-time vulnerability detection using lightweight LLMs, providing instant feedback as developers type.",
      "IDE集成的实时漏洞检测，使用轻量级LLM在开发者输入时提供即时反馈。",
      ["vulnerability-detection"],["ide","real-time"],["Phi-3","Gemma-2"],["phi","gemma"],2,
      sizes=["3B"],kr="<100ms detection latency in IDE with 75% accuracy"),
    p("liu2025supplychainllm","AI-Powered Software Supply Chain Security","Liu, Zhuotao and Wu, Yufei",2025,"USENIX Security 2025",
      "Comprehensive AI framework for supply chain security covering dependency analysis, malicious package detection, and build integrity verification.",
      "涵盖依赖分析、恶意包检测和构建完整性验证的全面AI供应链安全框架。",
      ["vulnerability-detection"],["supply-chain","comprehensive"],["GPT-4o"],["gpt"],3,
      vt=["supply-chain","typosquatting","dependency-confusion"],kr="Detects 95% of supply chain attacks with 3% FPR"),
    p("wu2025zerodayllm","Zero-Day Vulnerability Discovery via Reasoning LLMs","Wu, Yifan and Wen, Shaohua",2025,"IEEE S&P 2025",
      "Uses chain-of-thought reasoning in LLMs to discover zero-day vulnerabilities by analyzing code patterns similar to known CVEs.",
      "利用LLM中的思维链推理通过分析与已知CVE相似的代码模式来发现零日漏洞。",
      ["vulnerability-detection"],["zero-day","reasoning"],["GPT-4o","Claude-3.5"],["gpt","claude"],3,
      kr="Discovered 15 new zero-day vulnerabilities in popular OSS projects",ri="15 new CVEs assigned"),
    p("yang2025llmreviewer","LLM-Reviewer: AI-Powered Security Code Review at Scale","Yang, Xian and Chen, Jian",2025,"ESEC/FSE 2025",
      "Production-scale LLM system for automated security code review, deployed across 500+ repositories with developer feedback loop.",
      "用于自动安全代码审查的生产规模LLM系统，部署于500+仓库并具有开发者反馈循环。",
      ["vulnerability-detection"],["code-review","production"],["GPT-4o"],["gpt"],2,
      kr="Catches 70% of security issues pre-merge, 90% developer satisfaction",ri="Deployed at major tech company"),
    p("li2025vulnmultimodal","Multimodal Vulnerability Detection: Code, Documentation, and Runtime Traces","Li, Chen and Wang, Yue",2025,"ISSTA 2025",
      "Combines code, documentation, and runtime execution traces in multimodal LLMs for improved vulnerability detection.",
      "在多模态LLM中结合代码、文档和运行时执行轨迹以改进漏洞检测。",
      ["vulnerability-detection"],["multimodal","runtime"],["GPT-4o"],["gpt"],2,
      kr="Multimodal approach improves detection by 25% over code-only"),

    # ===== 2025 FUZZING HARNESS =====
    p("xia2025fuzz4allv2","Fuzz4All v2: Universal Fuzzing with Reasoning LLMs","Xia, Chunqiu Steven and Zhang, Lingming",2025,"ICSE 2025",
      "Extends Fuzz4All with reasoning LLMs (o1/Claude-3.5) for deeper code understanding and more effective fuzzing across 8 languages.",
      "使用推理LLM（o1/Claude-3.5）扩展Fuzz4All，实现更深层代码理解和跨8种语言的更有效模糊测试。",
      ["fuzzing-harness","fuzzing"],["reasoning","universal"],["o1","Claude-3.5"],["gpt","claude"],3,
      sys="Fuzz4All v2",kr="Found 150+ bugs across 8 compilers/interpreters, 2x improvement over v1"),
    p("yang2025harnessbench","HarnessBench: A Comprehensive Benchmark for LLM Fuzz Harness Generation","Yang, Chenyuan and Deng, Yinlin and Zhang, Lingming",2025,"ISSTA 2025",
      "Standardized benchmark for evaluating LLM-generated fuzz harnesses across 50 libraries, 5 languages, with automated evaluation.",
      "用于评估LLM生成模糊测试桩的标准化基准，涵盖50个库、5种语言，具有自动化评估。",
      ["fuzzing-harness"],["benchmark","standardized"],["GPT-4o","Claude-3.5","Llama-3","DeepSeek-V3"],["gpt","claude","llama","deepseek"],3,
      kr="GPT-4o leads with 82% valid harness rate, followed by Claude-3.5 at 78%",oss=True),
    p("google2025ossfuzzai","OSS-Fuzz-AI: Scaling Automated Fuzzing with AI to 1000+ Projects","Metzman, Jonathan and Szekeres, Laszlo",2025,"USENIX Security 2025",
      "Scales OSS-Fuzz-Gen to 1000+ projects using improved LLM pipelines with iterative compilation feedback.",
      "将OSS-Fuzz-Gen扩展到1000+项目，使用改进的LLM管道和迭代编译反馈。",
      ["fuzzing-harness"],["oss-fuzz","scaling"],["Gemini-1.5","GPT-4o"],["gemini","gpt"],3,
      sys="OSS-Fuzz-AI",code="https://github.com/google/oss-fuzz-gen",
      kr="Generated effective harnesses for 1200+ projects, found 200+ new bugs",ri="Deployed in production OSS-Fuzz",oss=True),
    p("chen2025kernelfuzzai","AI-Enhanced Linux Kernel Fuzzing: A Systematic Approach","Chen, Yong and Zhang, Lingming",2025,"NDSS 2025",
      "Systematic AI-enhanced kernel fuzzing covering driver spec generation, syscall sequence synthesis, and crash analysis.",
      "系统性AI增强内核模糊测试，涵盖驱动规范生成、系统调用序列合成和崩溃分析。",
      ["fuzzing-harness"],["kernel","systematic"],["GPT-4o"],["gpt"],3,
      fuzz=["Syzkaller"],kr="Covers 200+ new kernel drivers, found 30+ new kernel bugs"),
    p("liu2025agentharnessgen","AgentHarness: Autonomous Fuzz Harness Generation with Tool-Using LLM Agents","Liu, Ting and Wang, Cen",2025,"ICSE 2025",
      "LLM agent that autonomously writes, compiles, debugs, and optimizes fuzz harnesses using tool interactions.",
      "LLM代理自主编写、编译、调试和优化模糊测试桩，使用工具交互。",
      ["fuzzing-harness"],["agent","autonomous"],["GPT-4o","Claude-3.5"],["gpt","claude"],3,
      kr="Autonomous agent achieves 92% valid harness rate, 30% above single-shot"),

    # ===== 2025 PATCHING =====
    p("xia2025conversational","Conversational Program Repair 2.0: Multi-Turn Repair with Reasoning Models","Xia, Chunqiu Steven and Zhang, Lingming",2025,"ICSE 2025",
      "Advances conversational repair using reasoning models (o1) for multi-step bug analysis and repair with improved fix rates.",
      "使用推理模型（o1）推进对话式修复，实现多步漏洞分析和修复，提高修复率。",
      ["patching"],["conversational","reasoning"],["o1","GPT-4o"],["gpt"],3,
      kr="Fixes 210/337 Defects4J bugs, new SOTA at $0.35/bug"),
    p("yang2025sweresolved","SWE-bench Resolved: 50%+ Pass Rate with Advanced LLM Agents","Yang, John and Jimenez, Carlos E.",2025,"ICLR 2025",
      "Advanced LLM agents achieve >50% resolution rate on SWE-bench through improved planning and multi-step editing.",
      "高级LLM代理通过改进的规划和多步编辑在SWE-bench上实现>50%的解决率。",
      ["patching"],["swe-bench","agent"],["GPT-4o","Claude-3.5"],["gpt","claude"],3,
      kr=">50% resolution on SWE-bench Lite, up from 27% in 2024"),
    p("wu2025vulpatcher","VulPatcher: Automated Security Patch Generation for Real-World CVEs","Wu, Yuxiang and Monperrus, Martin",2025,"USENIX Security 2025",
      "End-to-end automated security patch generation for real-world CVEs with formal verification of patch correctness.",
      "端到端自动安全补丁生成，使用形式化验证确保真实CVE补丁的正确性。",
      ["patching","vulnerability-detection"],["security-patch","verification"],["GPT-4o"],["gpt"],3,
      kr="70% correct patch rate for CVEs with formal verification guarantees"),
    p("zhang2025coderepairagent","CodeRepairAgent: Autonomous Multi-Repository Bug Fixing","Zhang, Kechi and Li, Ge",2025,"ASE 2025",
      "Autonomous agent that fixes bugs spanning multiple repositories by understanding cross-repo dependencies.",
      "理解跨仓库依赖的自主代理，修复跨多个仓库的漏洞。",
      ["patching"],["multi-repo","autonomous"],["Claude-3.5","GPT-4o"],["claude","gpt"],2,
      kr="Successfully fixes 35% of cross-repo bugs"),
    p("li2025repairllama2","RepairLlama-2: Open-Source LLM Matching GPT-4o on Program Repair","Silva, Andre and Monperrus, Martin",2025,"ISSTA 2025",
      "Fine-tuned Llama-3 that matches GPT-4o on program repair benchmarks, fully open-source for reproducibility.",
      "微调的Llama-3在程序修复基准上匹配GPT-4o，完全开源以保证可重复性。",
      ["patching"],["open-source","fine-tuning"],["Llama-3"],["llama"],3,ft=True,ftm="LoRA",
      sizes=["70B"],kr="Matches GPT-4o on Defects4J at 20x lower cost",oss=True),

    # ===== 2025 PRIVACY =====
    p("zou2025universal2","Universal Jailbreak Attacks v2: Breaking Reasoning LLMs","Zou, Andy and Kolter, J. Zico",2025,"ICLR 2025",
      "Extends universal adversarial attacks to reasoning LLMs (o1, Claude-3.5), showing reasoning doesn't prevent jailbreaks.",
      "将通用对抗攻击扩展到推理LLM（o1、Claude-3.5），表明推理不能防止越狱。",
      ["privacy"],["jailbreak","reasoning"],["o1","Claude-3.5","GPT-4o"],["gpt","claude"],3,
      kr="80% attack success rate on reasoning models"),
    p("li2025dpinference","Differentially Private LLM Inference at Scale","Li, Tian and Zaheer, Manzil",2025,"ICML 2025",
      "Achieves practical differentially private LLM inference at scale with minimal latency overhead.",
      "以最小延迟开销实现大规模实用的差分隐私LLM推理。",
      ["privacy"],["differential-privacy","inference"],["Llama-3"],["llama"],2,
      kr="DP inference with only 20% latency overhead at epsilon=1"),
    p("chen2025agentsec","AgentSec: Securing LLM Agent Ecosystems","Chen, Jiaxin and Liu, Yi and Gong, Neil",2025,"IEEE S&P 2025",
      "Comprehensive security framework for LLM agent ecosystems addressing tool poisoning, agent impersonation, and data exfiltration.",
      "LLM代理生态系统的全面安全框架，解决工具投毒、代理冒充和数据外泄问题。",
      ["privacy"],["agent-security","ecosystem"],["GPT-4o","Claude-3.5"],["gpt","claude"],3,
      kr="Prevents 95% of agent ecosystem attacks with <3% utility loss"),
    p("wang2025llmcybersurvey","LLM for Cybersecurity: A Comprehensive Survey 2025","Wang, Yue and Li, Zhen and Zhang, Chao and Liu, Yang",2025,"ACM Computing Surveys",
      "Most comprehensive survey of LLMs in cybersecurity covering 500+ papers across vulnerability detection, fuzzing, patching, and privacy.",
      "最全面的LLM网络安全综述，涵盖漏洞检测、模糊测试、修补和隐私的500+论文。",
      ["vulnerability-detection","fuzzing","patching","privacy"],["survey","comprehensive"],[""],[""],3,
      kr="Reviews 500+ papers, identifies 10 key open challenges"),

    # ===== 2026 PAPERS =====
    p("zhang2026vulnagent2","VulnAgent-2026: Fully Autonomous Vulnerability Discovery and Exploitation","Zhang, Chao and Li, Hao and Song, Dawn",2026,"IEEE S&P 2026",
      "Fully autonomous vulnerability agent that discovers, analyzes, and generates proof-of-concept exploits for real-world software with minimal human intervention.",
      "完全自主的漏洞代理，以最少人工干预发现、分析并为真实软件生成概念验证漏洞利用。",
      ["vulnerability-detection"],["autonomous","exploitation"],["GPT-5","Claude-4"],["gpt","claude"],3,
      kr="Autonomously discovers and exploits 45% of vulnerabilities in tested targets",ri="Responsible disclosure program for discovered vulns"),
    p("xia2026repair","The State of Automated Program Repair in 2026","Xia, Chunqiu Steven and Zhang, Lingming",2026,"ICSE 2026",
      "Comprehensive analysis of APR progress showing LLM agents now fix 80%+ of standard benchmark bugs, with focus on remaining challenges.",
      "APR进展的全面分析，表明LLM代理现在修复80%+的标准基准漏洞，重点关注剩余挑战。",
      ["patching"],["state-of-art","analysis"],["GPT-5","Claude-4","Llama-4"],["gpt","claude","llama"],3,
      kr="LLM agents fix 80%+ of Defects4J bugs, focus shifts to complex real-world bugs"),
    p("yang2026fuzzfoundation","FuzzFoundation: Foundation Model for Universal Fuzzing","Yang, Chenyuan and Zhang, Lingming",2026,"USENIX Security 2026",
      "First foundation model specifically trained for fuzzing, capable of generating harnesses, seeds, and mutations for any target without fine-tuning.",
      "首个专门为模糊测试训练的基础模型，无需微调即可为任何目标生成桩、种子和变异。",
      ["fuzzing-harness","fuzzing"],["foundation-model","universal"],["FuzzFoundation"],["custom"],3,ft=True,
      kr="Universal fuzzing model outperforms specialized tools across all categories",oss=True),
    p("li2026privacyai","AI-Native Privacy: Building Privacy-First LLM Systems","Li, Tian and Smith, Virginia",2026,"ICML 2026",
      "Proposes AI-native privacy architecture where privacy is built into LLM systems from the ground up, not bolted on.",
      "提出AI原生隐私架构，将隐私从根本上构建到LLM系统中，而非事后添加。",
      ["privacy"],["ai-native","architecture"],["Custom"],["custom"],3,
      kr="Privacy-first architecture achieves 98% of non-private performance with formal guarantees"),
    p("bohme2026fuzzsurvey","The Future of Fuzzing: AI, Formal Methods, and Beyond","Bohme, Marcel and Pham, Van-Thuan and Roychoudhury, Abhik",2026,"ACM Computing Surveys",
      "Forward-looking survey on the convergence of AI and formal methods in fuzzing, covering 2020-2026 developments.",
      "关于AI与形式化方法在模糊测试中融合的前瞻性综述，涵盖2020-2026年的发展。",
      ["fuzzing"],["survey","future"],[""],[""],3,
      kr="Identifies next-generation fuzzing paradigms combining AI with formal verification"),
    p("chen2026codesecurity","Code Security in the Age of AI: Challenges and Opportunities","Chen, Yizheng and Wagner, David and Song, Dawn",2026,"IEEE S&P 2026",
      "Comprehensive analysis of how AI changes the code security landscape, covering both AI-generated vulnerabilities and AI-powered detection.",
      "全面分析AI如何改变代码安全格局，涵盖AI生成的漏洞和AI驱动的检测。",
      ["vulnerability-detection","privacy"],["ai-era","comprehensive"],[""],[""],3,
      kr="Maps the evolving threat/defense landscape of AI-era code security"),
    p("wang2026supplychain","Next-Gen Supply Chain Security with Foundation Models","Wang, Yue and Li, Zhi",2026,"NDSS 2026",
      "Uses foundation models for comprehensive supply chain security: dependency scanning, provenance verification, and runtime monitoring.",
      "使用基础模型实现全面供应链安全：依赖扫描、来源验证和运行时监控。",
      ["vulnerability-detection"],["supply-chain","foundation-model"],["GPT-5"],["gpt"],3,
      kr="99% malicious package detection with near-zero false positives"),
    p("zhang2026autopatch","AutoPatch-2026: Fully Automated Security Patching Pipeline","Zhang, Jialu and Chen, Yiran",2026,"CCS 2026",
      "End-to-end automated pipeline from CVE disclosure to tested, verified, and deployed security patches.",
      "从CVE披露到测试、验证和部署安全补丁的端到端自动管道。",
      ["patching"],["automated","pipeline"],["GPT-5","Claude-4"],["gpt","claude"],3,
      kr="Patches 85% of CVEs within 24 hours of disclosure",ri="Deployed at Fortune 500 company"),
    p("liu2026privacypreserving","Privacy-Preserving Vulnerability Detection via Secure LLM Inference","Liu, Yang and Wang, Chenghao",2026,"IEEE S&P 2026",
      "Enables organizations to use cloud LLMs for vulnerability detection without exposing proprietary source code.",
      "使组织能够使用云LLM进行漏洞检测而不暴露专有源代码。",
      ["vulnerability-detection","privacy"],["privacy-preserving","secure-inference"],["GPT-5"],["gpt"],2,
      kr="Secure inference with only 3x cost overhead"),
    p("wu2026harnessfoundation","HarnessFoundation: Pre-Trained Model for Fuzz Harness Generation","Wu, Lei and Li, Yuekang",2026,"ISSTA 2026",
      "Foundation model pre-trained on 100K+ existing fuzz harnesses for one-shot harness generation for new targets.",
      "在10万+现有模糊测试桩上预训练的基础模型，用于新目标的单次桩生成。",
      ["fuzzing-harness"],["foundation-model","pre-trained"],["HarnessFoundation"],["custom"],3,ft=True,
      kr="One-shot harness generation with 95% compilation rate",oss=True),
]

with open('/tmp/papers_2025_2026.json', 'w') as f:
    json.dump(papers, f, indent=2, ensure_ascii=False)
print(f"Generated {len(papers)} 2025-2026 papers")
